<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Errors;

class CreateCustomerDocumentNotFoundDwollaV1HalJSONExceptionThrowable extends \RuntimeException
{
    public CreateCustomerDocumentNotFoundDwollaV1HalJSONException $container;

    public function __construct(string $message, int $statusCode, CreateCustomerDocumentNotFoundDwollaV1HalJSONException $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}