<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Errors;

use Dwolla\Models\Components;
use Dwolla\Utils;
/** InvalidCardTokenError - Error returned when attempting to create a debit card funding source with an invalid card token */
class InvalidCardTokenError
{
    /**
     *
     * @var string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    public string $code;

    /**
     *
     * @var string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    public string $message;

    /**
     *
     * @var Components\InvalidCardTokenErrorEmbedded $embedded
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_embedded')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\InvalidCardTokenErrorEmbedded')]
    public Components\InvalidCardTokenErrorEmbedded $embedded;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
    #[\Speakeasy\Serializer\Annotation\Exclude]

    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;

    /**
     * @param  string  $code
     * @param  string  $message
     * @param  Components\InvalidCardTokenErrorEmbedded  $embedded
     * @param  ?\Psr\Http\Message\ResponseInterface  $rawResponse
     * @phpstan-pure
     */
    public function __construct(string $code, string $message, Components\InvalidCardTokenErrorEmbedded $embedded, ?\Psr\Http\Message\ResponseInterface $rawResponse = null)
    {
        $this->code = $code;
        $this->message = $message;
        $this->embedded = $embedded;
        $this->rawResponse = $rawResponse;
    }

    public function toException(): InvalidCardTokenErrorThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = $this->code;

        return new InvalidCardTokenErrorThrowable($message, (int) $code, $this);
    }
}