<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Errors;

use Dwolla\Models\Components;
use Dwolla\Utils;
class InvalidUrlFormatError
{
    /**
     *
     * @var ?string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $code = null;

    /**
     *
     * @var ?string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $message = null;

    /**
     *
     * @var ?Components\InvalidUrlFormatErrorEmbedded $embedded
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_embedded')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\InvalidUrlFormatErrorEmbedded|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Components\InvalidUrlFormatErrorEmbedded $embedded = null;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
    #[\Speakeasy\Serializer\Annotation\Exclude]

    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;

    /**
     * @param  ?string  $code
     * @param  ?string  $message
     * @param  ?Components\InvalidUrlFormatErrorEmbedded  $embedded
     * @param  ?\Psr\Http\Message\ResponseInterface  $rawResponse
     * @phpstan-pure
     */
    public function __construct(?string $code = null, ?string $message = null, ?Components\InvalidUrlFormatErrorEmbedded $embedded = null, ?\Psr\Http\Message\ResponseInterface $rawResponse = null)
    {
        $this->code = $code;
        $this->message = $message;
        $this->embedded = $embedded;
        $this->rawResponse = $rawResponse;
    }

    public function toException(): InvalidUrlFormatErrorThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        if ($this->code !== null) {
            $code = $this->code;
        } else {
            $code = -1;
        }

        return new InvalidUrlFormatErrorThrowable($message, (int) $code, $this);
    }
}