<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Errors;

use Dwolla\Models\Components;
use Dwolla\Utils;
class InvalidOrRemovedCardDestinationError
{
    /**
     *
     * @var string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    public string $code;

    /**
     *
     * @var string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    public string $message;

    /**
     *
     * @var ?Components\InvalidOrRemovedCardDestinationErrorEmbedded $embedded
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_embedded')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\InvalidOrRemovedCardDestinationErrorEmbedded|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Components\InvalidOrRemovedCardDestinationErrorEmbedded $embedded = null;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
    #[\Speakeasy\Serializer\Annotation\Exclude]

    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;

    /**
     * @param  string  $code
     * @param  string  $message
     * @param  ?Components\InvalidOrRemovedCardDestinationErrorEmbedded  $embedded
     * @param  ?\Psr\Http\Message\ResponseInterface  $rawResponse
     * @phpstan-pure
     */
    public function __construct(string $code, string $message, ?Components\InvalidOrRemovedCardDestinationErrorEmbedded $embedded = null, ?\Psr\Http\Message\ResponseInterface $rawResponse = null)
    {
        $this->code = $code;
        $this->message = $message;
        $this->embedded = $embedded;
        $this->rawResponse = $rawResponse;
    }

    public function toException(): InvalidOrRemovedCardDestinationErrorThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = $this->code;

        return new InvalidOrRemovedCardDestinationErrorThrowable($message, (int) $code, $this);
    }
}