<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Errors;

use Dwolla\Utils;
/** NotFoundError - Error response schema for 404 NotFound */
class NotFoundError
{
    /**
     *
     * @var string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    public string $code;

    /**
     *
     * @var string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    public string $message;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
    #[\Speakeasy\Serializer\Annotation\Exclude]

    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;

    /**
     * @param  string  $code
     * @param  string  $message
     * @param  ?\Psr\Http\Message\ResponseInterface  $rawResponse
     * @phpstan-pure
     */
    public function __construct(string $code, string $message, ?\Psr\Http\Message\ResponseInterface $rawResponse = null)
    {
        $this->code = $code;
        $this->message = $message;
        $this->rawResponse = $rawResponse;
    }

    public function toException(): NotFoundErrorThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = $this->code;

        return new NotFoundErrorThrowable($message, (int) $code, $this);
    }
}