<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Errors;

class ResponseBodyForbiddenException2Throwable extends \RuntimeException
{
    public ResponseBodyForbiddenException2 $container;

    public function __construct(string $message, int $statusCode, ResponseBodyForbiddenException2 $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}