<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Errors;

use Dwolla\Models\Components;
use Dwolla\Utils;
/**
 * UpdateFundingSourceValidationError - Validation error returned when an update request cannot be applied. The specific problem is
 *
 * described by the embedded error's `code`, `message`, and `path`. Common cases:
 * - no updateable field was provided (`Invalid` at `/`)
 * - bank fields were sent to a card funding source (`NotAllowed` at `/routingNumber`)
 * - card fields were sent to a bank funding source (`NotAllowed` at `/cardDetails`)
 * - a `cardDetails` value failed validation, such as `countryOfBirth` not being exactly 2 characters
 *
 */
class UpdateFundingSourceValidationError
{
    /**
     *
     * @var string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    public string $code;

    /**
     *
     * @var string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    public string $message;

    /**
     *
     * @var \Dwolla\Models\Components\UpdateFundingSourceValidationErrorEmbedded $embedded
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_embedded')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\UpdateFundingSourceValidationErrorEmbedded')]
    public Components\UpdateFundingSourceValidationErrorEmbedded $embedded;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
    #[\Speakeasy\Serializer\Annotation\Exclude]

    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;

    /**
     * @param  string  $code
     * @param  string  $message
     * @param  \Dwolla\Models\Components\UpdateFundingSourceValidationErrorEmbedded  $embedded
     * @param  ?\Psr\Http\Message\ResponseInterface  $rawResponse
     * @phpstan-pure
     */
    public function __construct(string $code, string $message, Components\UpdateFundingSourceValidationErrorEmbedded $embedded, ?\Psr\Http\Message\ResponseInterface $rawResponse = null)
    {
        $this->code = $code;
        $this->message = $message;
        $this->embedded = $embedded;
        $this->rawResponse = $rawResponse;
    }

    public function toException(): UpdateFundingSourceValidationErrorThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = $this->code;

        return new UpdateFundingSourceValidationErrorThrowable($message, (int) $code, $this);
    }
}