<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Errors;

class WithdrawProcessingChannelNotSupportedErrorThrowable extends \RuntimeException
{
    public WithdrawProcessingChannelNotSupportedError $container;

    public function __construct(string $message, int $statusCode, WithdrawProcessingChannelNotSupportedError $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}