<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


/** BankBalanceResponse - Response for retrieving balance of a bank account verified through Open Banking */
class BankBalanceResponse
{
    /**
     *
     * @var GetFundingSourceBalanceLinks1 $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\GetFundingSourceBalanceLinks1')]
    public GetFundingSourceBalanceLinks1 $links;

    /**
     *
     * @var Available1 $available
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('available')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\Available1')]
    public Available1 $available;

    /**
     *
     * @var Closing $closing
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('closing')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\Closing')]
    public Closing $closing;

    /**
     *
     * @var string $lastUpdated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastUpdated')]
    public string $lastUpdated;

    /**
     * @param  GetFundingSourceBalanceLinks1  $links
     * @param  Available1  $available
     * @param  Closing  $closing
     * @param  string  $lastUpdated
     * @phpstan-pure
     */
    public function __construct(GetFundingSourceBalanceLinks1 $links, Available1 $available, Closing $closing, string $lastUpdated)
    {
        $this->links = $links;
        $this->available = $available;
        $this->closing = $closing;
        $this->lastUpdated = $lastUpdated;
    }
}