<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Utils\SpeakeasyMetadata;
class CertifyBeneficialOwnershipForCustomerRequest
{
    /**
     * Customer unique identifier
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     * Parameters for certifying beneficial ownership for a Customer
     *
     * @var CertifyBeneficialOwnershipForCustomerRequestBody $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public CertifyBeneficialOwnershipForCustomerRequestBody $body;

    /**
     * @param  string  $id
     * @param  CertifyBeneficialOwnershipForCustomerRequestBody  $body
     * @phpstan-pure
     */
    public function __construct(string $id, CertifyBeneficialOwnershipForCustomerRequestBody $body)
    {
        $this->id = $id;
        $this->body = $body;
    }
}