<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Models\Components;
use Dwolla\Utils\SpeakeasyMetadata;
class CreateReAuthExchangeSessionRequest
{
    /**
     * Exchange's unique identifier
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     * Request body containing the redirect URL.
     *
     * Required for:
     * - Plaid mobile sessions
     * Not required for:
     * - Plaid web sessions
     *
     *
     * @var Components\CreateReAuthExchangeSessionForWeb|Components\CreateReAuthExchangeSessionWithRedirect|null $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/vnd.dwolla.v1.hal+json')]
    public Components\CreateReAuthExchangeSessionForWeb|Components\CreateReAuthExchangeSessionWithRedirect|null $body = null;

    /**
     * @param  string  $id
     * @param  Components\CreateReAuthExchangeSessionForWeb|Components\CreateReAuthExchangeSessionWithRedirect|null  $body
     * @phpstan-pure
     */
    public function __construct(string $id, Components\CreateReAuthExchangeSessionForWeb|Components\CreateReAuthExchangeSessionWithRedirect|null $body = null)
    {
        $this->id = $id;
        $this->body = $body;
    }
}