<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Utils\SpeakeasyMetadata;
class CreateBeneficialOwnerDocumentRequest
{
    /**
     * beneficial owner unique identifier
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     * Upload a document for a beneficial owner.
     *
     * @var CreateBeneficialOwnerDocumentRequestBody $body
     */
    #[SpeakeasyMetadata('request:mediaType=multipart/form-data')]
    public CreateBeneficialOwnerDocumentRequestBody $body;

    /**
     * @param  string  $id
     * @param  CreateBeneficialOwnerDocumentRequestBody  $body
     * @phpstan-pure
     */
    public function __construct(string $id, CreateBeneficialOwnerDocumentRequestBody $body)
    {
        $this->id = $id;
        $this->body = $body;
    }
}