<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Utils\SpeakeasyMetadata;
class CreateCustomerLabelRequest
{
    /**
     * ID of customer to create a label for
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     * Parameters to create a customer label
     *
     * @var CreateCustomerLabelRequestBody $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public CreateCustomerLabelRequestBody $body;

    /**
     * @param  string  $id
     * @param  CreateCustomerLabelRequestBody  $body
     * @phpstan-pure
     */
    public function __construct(string $id, CreateCustomerLabelRequestBody $body)
    {
        $this->id = $id;
        $this->body = $body;
    }
}