<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


class CreateLabelReallocationLinks
{
    /**
     *
     * @var ?\Dwolla\Models\Operations\FromT $from
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\FromT|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?FromT $from = null;

    /**
     *
     * @var ?\Dwolla\Models\Operations\To $to
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('to')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\To|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?To $to = null;

    /**
     * @param  ?\Dwolla\Models\Operations\FromT  $from
     * @param  ?\Dwolla\Models\Operations\To  $to
     * @phpstan-pure
     */
    public function __construct(?FromT $from = null, ?To $to = null)
    {
        $this->from = $from;
        $this->to = $to;
    }
}