<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


/** CreateClientTokenResponseBody - Client token created successfully */
class CreateClientTokenResponseBody
{
    /**
     * The client token that can be used with drop-in components
     *
     * @var string $token
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('token')]
    public string $token;

    /**
     * @param  string  $token
     * @phpstan-pure
     */
    public function __construct(string $token)
    {
        $this->token = $token;
    }
}