<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


/** CreateLabelReallocationRequest - Parameters to create a label reallocation */
class CreateLabelReallocationRequest
{
    /**
     *
     * @var CreateLabelReallocationLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\CreateLabelReallocationLinks')]
    public CreateLabelReallocationLinks $links;

    /**
     *
     * @var CreateLabelReallocationAmount $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\CreateLabelReallocationAmount')]
    public CreateLabelReallocationAmount $amount;

    /**
     * @param  CreateLabelReallocationLinks  $links
     * @param  CreateLabelReallocationAmount  $amount
     * @phpstan-pure
     */
    public function __construct(CreateLabelReallocationLinks $links, CreateLabelReallocationAmount $amount)
    {
        $this->links = $links;
        $this->amount = $amount;
    }
}