<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Utils\SpeakeasyMetadata;
class CreateApplicationAccessTokenSecurity
{
    /**
     *
     * @var string $basicAuth
     */
    #[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=header,name=Authorization')]
    public string $basicAuth;

    /**
     * @param  string  $basicAuth
     * @phpstan-pure
     */
    public function __construct(string $basicAuth)
    {
        $this->basicAuth = $basicAuth;
    }
}