<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Models\Components;
class Fee
{
    /**
     *
     * @var ?\Dwolla\Models\Operations\FeeLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\FeeLinks|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?FeeLinks $links = null;

    /**
     *
     * @var ?\Dwolla\Models\Components\TransferAmount $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\TransferAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Components\TransferAmount $amount = null;

    /**
     * @param  ?\Dwolla\Models\Operations\FeeLinks  $links
     * @param  ?\Dwolla\Models\Components\TransferAmount  $amount
     * @phpstan-pure
     */
    public function __construct(?FeeLinks $links = null, ?Components\TransferAmount $amount = null)
    {
        $this->links = $links;
        $this->amount = $amount;
    }
}