<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


class GetFundingSourceBalanceLinks2
{
    /**
     *
     * @var ?GetFundingSourceBalanceSelf2 $self
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('self')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\GetFundingSourceBalanceSelf2|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?GetFundingSourceBalanceSelf2 $self = null;

    /**
     *
     * @var ?FundingSource2 $fundingSource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('funding-source')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\FundingSource2|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?FundingSource2 $fundingSource = null;

    /**
     * @param  ?GetFundingSourceBalanceSelf2  $self
     * @param  ?FundingSource2  $fundingSource
     * @phpstan-pure
     */
    public function __construct(?GetFundingSourceBalanceSelf2 $self = null, ?FundingSource2 $fundingSource = null)
    {
        $this->self = $self;
        $this->fundingSource = $fundingSource;
    }
}