<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Models\Components;
/** GetTransferFailureReasonResponseBody - successful operation */
class GetTransferFailureReasonResponseBody
{
    /**
     *
     * @var string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    public string $code;

    /**
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * $links
     *
     * @var ?array<string, Components\HalLink> $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, \Dwolla\Models\Components\HalLink>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $links = null;

    /**
     *
     * @var ?string $explanation
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('explanation')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $explanation = null;

    /**
     * @param  string  $code
     * @param  string  $description
     * @param  ?array<string, Components\HalLink>  $links
     * @param  ?string  $explanation
     * @phpstan-pure
     */
    public function __construct(string $code, string $description, ?array $links = null, ?string $explanation = null)
    {
        $this->code = $code;
        $this->description = $description;
        $this->links = $links;
        $this->explanation = $explanation;
    }
}