<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Models\Components;
/** GetVanRoutingResponseBody - successful operation */
class GetVanRoutingResponseBody
{
    /**
     * $links
     *
     * @var ?array<string, Components\HalLink> $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, \Dwolla\Models\Components\HalLink>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $links = null;

    /**
     *
     * @var ?string $accountNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accountNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $accountNumber = null;

    /**
     *
     * @var ?string $routingNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('routingNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $routingNumber = null;

    /**
     * @param  ?array<string, Components\HalLink>  $links
     * @param  ?string  $accountNumber
     * @param  ?string  $routingNumber
     * @phpstan-pure
     */
    public function __construct(?array $links = null, ?string $accountNumber = null, ?string $routingNumber = null)
    {
        $this->links = $links;
        $this->accountNumber = $accountNumber;
        $this->routingNumber = $routingNumber;
    }
}