<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


/** Must be set to "client_credentials" */
enum GrantType: string
{
    case ClientCredentials = 'client_credentials';
}
