<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


class InitiateMassPaymentAchDetailsDestination
{
    /**
     *
     * @var ?ItemAddenda $addenda
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('addenda')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\ItemAddenda|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ItemAddenda $addenda = null;

    /**
     * @param  ?ItemAddenda  $addenda
     * @phpstan-pure
     */
    public function __construct(?ItemAddenda $addenda = null)
    {
        $this->addenda = $addenda;
    }
}