<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


class InitiateOrVerifyMicroDepositsLinks
{
    /**
     *
     * @var ?InitiateOrVerifyMicroDepositsSelf $self
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('self')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\InitiateOrVerifyMicroDepositsSelf|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InitiateOrVerifyMicroDepositsSelf $self = null;

    /**
     * @param  ?InitiateOrVerifyMicroDepositsSelf  $self
     * @phpstan-pure
     */
    public function __construct(?InitiateOrVerifyMicroDepositsSelf $self = null)
    {
        $this->self = $self;
    }
}