<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


class InitiateTransferAchDetailsDestination
{
    /**
     *
     * @var ?\Dwolla\Models\Operations\InitiateTransferDestinationAddenda $addenda
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('addenda')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\InitiateTransferDestinationAddenda|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InitiateTransferDestinationAddenda $addenda = null;

    /**
     * @param  ?\Dwolla\Models\Operations\InitiateTransferDestinationAddenda  $addenda
     * @phpstan-pure
     */
    public function __construct(?InitiateTransferDestinationAddenda $addenda = null)
    {
        $this->addenda = $addenda;
    }
}