<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Utils\SpeakeasyMetadata;
class InitiateMassPaymentRequest
{
    /**
     * Parameters for initiating a mass payment
     *
     * @var InitiateMassPaymentRequestBody $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public InitiateMassPaymentRequestBody $body;

    /**
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Idempotency-Key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  InitiateMassPaymentRequestBody  $body
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(InitiateMassPaymentRequestBody $body, ?string $idempotencyKey = null)
    {
        $this->body = $body;
        $this->idempotencyKey = $idempotencyKey;
    }
}