<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


class InitiateTransferLinks
{
    /**
     *
     * @var ?\Dwolla\Models\Operations\InitiateTransferLinksSource $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\InitiateTransferLinksSource|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InitiateTransferLinksSource $source = null;

    /**
     *
     * @var ?\Dwolla\Models\Operations\InitiateTransferLinksDestination $destination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\InitiateTransferLinksDestination|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InitiateTransferLinksDestination $destination = null;

    /**
     * @param  ?\Dwolla\Models\Operations\InitiateTransferLinksSource  $source
     * @param  ?\Dwolla\Models\Operations\InitiateTransferLinksDestination  $destination
     * @phpstan-pure
     */
    public function __construct(?InitiateTransferLinksSource $source = null, ?InitiateTransferLinksDestination $destination = null)
    {
        $this->source = $source;
        $this->destination = $destination;
    }
}