<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


class InitiateTransferAchDetails
{
    /**
     *
     * @var ?InitiateTransferAchDetailsSource $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\InitiateTransferAchDetailsSource|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InitiateTransferAchDetailsSource $source = null;

    /**
     *
     * @var ?InitiateTransferAchDetailsDestination $destination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\InitiateTransferAchDetailsDestination|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InitiateTransferAchDetailsDestination $destination = null;

    /**
     * @param  ?InitiateTransferAchDetailsSource  $source
     * @param  ?InitiateTransferAchDetailsDestination  $destination
     * @phpstan-pure
     */
    public function __construct(?InitiateTransferAchDetailsSource $source = null, ?InitiateTransferAchDetailsDestination $destination = null)
    {
        $this->source = $source;
        $this->destination = $destination;
    }
}