<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Models\Components;
/** InitiateTransferRequestBody - Parameters to initiate a transfer */
class InitiateTransferRequestBody
{
    /**
     *
     * @var InitiateTransferLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\InitiateTransferLinks')]
    public InitiateTransferLinks $links;

    /**
     *
     * @var Components\TransferAmount $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\TransferAmount')]
    public Components\TransferAmount $amount;

    /**
     *
     * @var ?InitiateTransferMetadata $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\InitiateTransferMetadata|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InitiateTransferMetadata $metadata = null;

    /**
     * $fees
     *
     * @var ?array<Fee> $fees
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fees')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dwolla\Models\Operations\Fee>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $fees = null;

    /**
     *
     * @var ?InitiateTransferClearing $clearing
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('clearing')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\InitiateTransferClearing|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InitiateTransferClearing $clearing = null;

    /**
     *
     * @var ?InitiateTransferAchDetails $achDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('achDetails')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\InitiateTransferAchDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InitiateTransferAchDetails $achDetails = null;

    /**
     * Real-Time Payments (RTP) specific transaction details.
     *
     * @var ?RtpDetails $rtpDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rtpDetails')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\RtpDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?RtpDetails $rtpDetails = null;

    /**
     * Instant Payments specific transaction details for both RTP and FedNow networks.
     *
     * @var ?InstantDetails $instantDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('instantDetails')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\InstantDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InstantDetails $instantDetails = null;

    /**
     *
     * @var ?string $correlationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('correlationId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $correlationId = null;

    /**
     *
     * @var ?InitiateTransferProcessingChannel $processingChannel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('processingChannel')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\InitiateTransferProcessingChannel|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InitiateTransferProcessingChannel $processingChannel = null;

    /**
     * @param  InitiateTransferLinks  $links
     * @param  Components\TransferAmount  $amount
     * @param  ?InitiateTransferMetadata  $metadata
     * @param  ?array<Fee>  $fees
     * @param  ?InitiateTransferClearing  $clearing
     * @param  ?InitiateTransferAchDetails  $achDetails
     * @param  ?RtpDetails  $rtpDetails
     * @param  ?InstantDetails  $instantDetails
     * @param  ?string  $correlationId
     * @param  ?InitiateTransferProcessingChannel  $processingChannel
     * @phpstan-pure
     */
    public function __construct(InitiateTransferLinks $links, Components\TransferAmount $amount, ?InitiateTransferMetadata $metadata = null, ?array $fees = null, ?InitiateTransferClearing $clearing = null, ?InitiateTransferAchDetails $achDetails = null, ?RtpDetails $rtpDetails = null, ?InstantDetails $instantDetails = null, ?string $correlationId = null, ?InitiateTransferProcessingChannel $processingChannel = null)
    {
        $this->links = $links;
        $this->amount = $amount;
        $this->metadata = $metadata;
        $this->fees = $fees;
        $this->clearing = $clearing;
        $this->achDetails = $achDetails;
        $this->rtpDetails = $rtpDetails;
        $this->instantDetails = $instantDetails;
        $this->correlationId = $correlationId;
        $this->processingChannel = $processingChannel;
    }
}