<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


/** InstantDetails - Instant Payments specific transaction details for both RTP and FedNow networks. */
class InstantDetails
{
    /**
     * Instant payment details for the destination
     *
     * @var ?InstantDetailsDestination $destination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\InstantDetailsDestination|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InstantDetailsDestination $destination = null;

    /**
     * @param  ?InstantDetailsDestination  $destination
     * @phpstan-pure
     */
    public function __construct(?InstantDetailsDestination $destination = null)
    {
        $this->destination = $destination;
    }
}