<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Models\Components;
class Item
{
    /**
     *
     * @var ?ItemLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\ItemLinks|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ItemLinks $links = null;

    /**
     *
     * @var ?Components\TransferAmount $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\TransferAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Components\TransferAmount $amount = null;

    /**
     *
     * @var ?InitiateMassPaymentProcessingChannel $processingChannel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('processingChannel')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\InitiateMassPaymentProcessingChannel|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InitiateMassPaymentProcessingChannel $processingChannel = null;

    /**
     *
     * @var ?ItemMetadata $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\ItemMetadata|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ItemMetadata $metadata = null;

    /**
     *
     * @var ?ItemClearing $clearing
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('clearing')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\ItemClearing|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ItemClearing $clearing = null;

    /**
     *
     * @var ?ItemAchDetails $achDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('achDetails')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\ItemAchDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ItemAchDetails $achDetails = null;

    /**
     *
     * @var ?string $correlationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('correlationId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $correlationId = null;

    /**
     * @param  ?ItemLinks  $links
     * @param  ?Components\TransferAmount  $amount
     * @param  ?InitiateMassPaymentProcessingChannel  $processingChannel
     * @param  ?ItemMetadata  $metadata
     * @param  ?ItemClearing  $clearing
     * @param  ?ItemAchDetails  $achDetails
     * @param  ?string  $correlationId
     * @phpstan-pure
     */
    public function __construct(?ItemLinks $links = null, ?Components\TransferAmount $amount = null, ?InitiateMassPaymentProcessingChannel $processingChannel = null, ?ItemMetadata $metadata = null, ?ItemClearing $clearing = null, ?ItemAchDetails $achDetails = null, ?string $correlationId = null)
    {
        $this->links = $links;
        $this->amount = $amount;
        $this->processingChannel = $processingChannel;
        $this->metadata = $metadata;
        $this->clearing = $clearing;
        $this->achDetails = $achDetails;
        $this->correlationId = $correlationId;
    }
}