<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


class ItemAchDetails
{
    /**
     *
     * @var ?InitiateMassPaymentAchDetailsDestination $destination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\InitiateMassPaymentAchDetailsDestination|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InitiateMassPaymentAchDetailsDestination $destination = null;

    /**
     * @param  ?InitiateMassPaymentAchDetailsDestination  $destination
     * @phpstan-pure
     */
    public function __construct(?InitiateMassPaymentAchDetailsDestination $destination = null)
    {
        $this->destination = $destination;
    }
}