<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


/** ListMassPaymentItemsResponseBody - successful operation */
class ListMassPaymentItemsResponseBody
{
    /**
     *
     * @var ?ListMassPaymentItemsLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\ListMassPaymentItemsLinks|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ListMassPaymentItemsLinks $links = null;

    /**
     *
     * @var ?ListMassPaymentItemsEmbedded $embedded
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_embedded')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\ListMassPaymentItemsEmbedded|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ListMassPaymentItemsEmbedded $embedded = null;

    /**
     *
     * @var ?int $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $total = null;

    /**
     * @param  ?ListMassPaymentItemsLinks  $links
     * @param  ?ListMassPaymentItemsEmbedded  $embedded
     * @param  ?int  $total
     * @phpstan-pure
     */
    public function __construct(?ListMassPaymentItemsLinks $links = null, ?ListMassPaymentItemsEmbedded $embedded = null, ?int $total = null)
    {
        $this->links = $links;
        $this->embedded = $embedded;
        $this->total = $total;
    }
}