<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Models\Components;
class ListWebhooksEmbedded
{
    /**
     * $webhooks
     *
     * @var ?array<Components\Webhook> $webhooks
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('webhooks')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dwolla\Models\Components\Webhook>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $webhooks = null;

    /**
     * @param  ?array<Components\Webhook>  $webhooks
     * @phpstan-pure
     */
    public function __construct(?array $webhooks = null)
    {
        $this->webhooks = $webhooks;
    }
}