<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


class ListMassPaymentItemsLinks
{
    /**
     *
     * @var ?\Dwolla\Models\Operations\ListMassPaymentItemsSelf $self
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('self')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\ListMassPaymentItemsSelf|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ListMassPaymentItemsSelf $self = null;

    /**
     *
     * @var ?\Dwolla\Models\Operations\ListMassPaymentItemsFirst $first
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('first')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\ListMassPaymentItemsFirst|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ListMassPaymentItemsFirst $first = null;

    /**
     *
     * @var ?\Dwolla\Models\Operations\ListMassPaymentItemsLast $last
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\ListMassPaymentItemsLast|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ListMassPaymentItemsLast $last = null;

    /**
     * @param  ?\Dwolla\Models\Operations\ListMassPaymentItemsSelf  $self
     * @param  ?\Dwolla\Models\Operations\ListMassPaymentItemsFirst  $first
     * @param  ?\Dwolla\Models\Operations\ListMassPaymentItemsLast  $last
     * @phpstan-pure
     */
    public function __construct(?ListMassPaymentItemsSelf $self = null, ?ListMassPaymentItemsFirst $first = null, ?ListMassPaymentItemsLast $last = null)
    {
        $this->self = $self;
        $this->first = $first;
        $this->last = $last;
    }
}