<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Utils\SpeakeasyMetadata;
class ListCustomerLabelsRequest
{
    /**
     * ID of customer
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     * How many results to return
     *
     * @var ?string $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?string $limit = null;

    /**
     * How many results to skip
     *
     * @var ?string $offset
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?string $offset = null;

    /**
     * @param  string  $id
     * @param  ?string  $limit
     * @param  ?string  $offset
     * @phpstan-pure
     */
    public function __construct(string $id, ?string $limit = null, ?string $offset = null)
    {
        $this->id = $id;
        $this->limit = $limit;
        $this->offset = $offset;
    }
}