<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


/** ListWebhooksResponseBody - successful operation */
class ListWebhooksResponseBody
{
    /**
     *
     * @var ?ListWebhooksLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\ListWebhooksLinks|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ListWebhooksLinks $links = null;

    /**
     *
     * @var ?ListWebhooksEmbedded $embedded
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_embedded')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\ListWebhooksEmbedded|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ListWebhooksEmbedded $embedded = null;

    /**
     *
     * @var ?int $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $total = null;

    /**
     * @param  ?ListWebhooksLinks  $links
     * @param  ?ListWebhooksEmbedded  $embedded
     * @param  ?int  $total
     * @phpstan-pure
     */
    public function __construct(?ListWebhooksLinks $links = null, ?ListWebhooksEmbedded $embedded = null, ?int $total = null)
    {
        $this->links = $links;
        $this->embedded = $embedded;
        $this->total = $total;
    }
}