<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Utils\SpeakeasyMetadata;
class ListMassPaymentsRequest
{
    /**
     * Account's unique identifier
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     * Correlation ID to search by.
     *
     * @var ?string $correlationId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=correlationId')]
    public ?string $correlationId = null;

    /**
     * Maximum number of results to return
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * How many results to skip.
     *
     * @var ?int $offset
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?int $offset = null;

    /**
     * @param  string  $id
     * @param  ?int  $limit
     * @param  ?int  $offset
     * @param  ?string  $correlationId
     * @phpstan-pure
     */
    public function __construct(string $id, ?string $correlationId = null, ?int $limit = 25, ?int $offset = 0)
    {
        $this->id = $id;
        $this->correlationId = $correlationId;
        $this->limit = $limit;
        $this->offset = $offset;
    }
}