<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Models\Components;
class ListMassPaymentItemsEmbedded
{
    /**
     * $items
     *
     * @var ?array<Components\MassPaymentItem> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dwolla\Models\Components\MassPaymentItem>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $items = null;

    /**
     * @param  ?array<Components\MassPaymentItem>  $items
     * @phpstan-pure
     */
    public function __construct(?array $items = null)
    {
        $this->items = $items;
    }
}