<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


class ListWebhooksLinks
{
    /**
     *
     * @var ?ListWebhooksSelf $self
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('self')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\ListWebhooksSelf|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ListWebhooksSelf $self = null;

    /**
     *
     * @var ?ListWebhooksFirst $first
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('first')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\ListWebhooksFirst|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ListWebhooksFirst $first = null;

    /**
     *
     * @var ?ListWebhooksLast $last
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\ListWebhooksLast|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ListWebhooksLast $last = null;

    /**
     *
     * @var ?Next $next
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('next')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\Next|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Next $next = null;

    /**
     * @param  ?ListWebhooksSelf  $self
     * @param  ?ListWebhooksFirst  $first
     * @param  ?ListWebhooksLast  $last
     * @param  ?Next  $next
     * @phpstan-pure
     */
    public function __construct(?ListWebhooksSelf $self = null, ?ListWebhooksFirst $first = null, ?ListWebhooksLast $last = null, ?Next $next = null)
    {
        $this->self = $self;
        $this->first = $first;
        $this->last = $last;
        $this->next = $next;
    }
}