<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


class Question
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $text
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('text')]
    public string $text;

    /**
     * $answers
     *
     * @var array<QuestionAnswer> $answers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('answers')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dwolla\Models\Operations\QuestionAnswer>')]
    public array $answers;

    /**
     * @param  string  $id
     * @param  string  $text
     * @param  array<QuestionAnswer>  $answers
     * @phpstan-pure
     */
    public function __construct(string $id, string $text, array $answers)
    {
        $this->id = $id;
        $this->text = $text;
        $this->answers = $answers;
    }
}