<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


class QuestionAnswer
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $text
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('text')]
    public string $text;

    /**
     * @param  string  $id
     * @param  string  $text
     * @phpstan-pure
     */
    public function __construct(string $id, string $text)
    {
        $this->id = $id;
        $this->text = $text;
    }
}