<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


class RetrieveLabelReallocationLinks
{
    /**
     *
     * @var ?\Dwolla\Models\Operations\RetrieveLabelReallocationSelf $self
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('self')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\RetrieveLabelReallocationSelf|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?RetrieveLabelReallocationSelf $self = null;

    /**
     *
     * @var ?\Dwolla\Models\Operations\ToLedgerEntry $toLedgerEntry
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('to-ledger-entry')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\ToLedgerEntry|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ToLedgerEntry $toLedgerEntry = null;

    /**
     *
     * @var ?\Dwolla\Models\Operations\FromLedgerEntry $fromLedgerEntry
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from-ledger-entry')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\FromLedgerEntry|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?FromLedgerEntry $fromLedgerEntry = null;

    /**
     * @param  ?\Dwolla\Models\Operations\RetrieveLabelReallocationSelf  $self
     * @param  ?\Dwolla\Models\Operations\ToLedgerEntry  $toLedgerEntry
     * @param  ?\Dwolla\Models\Operations\FromLedgerEntry  $fromLedgerEntry
     * @phpstan-pure
     */
    public function __construct(?RetrieveLabelReallocationSelf $self = null, ?ToLedgerEntry $toLedgerEntry = null, ?FromLedgerEntry $fromLedgerEntry = null)
    {
        $this->self = $self;
        $this->toLedgerEntry = $toLedgerEntry;
        $this->fromLedgerEntry = $fromLedgerEntry;
    }
}