<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


/** RetrieveLabelReallocationResponseBody - successful operation */
class RetrieveLabelReallocationResponseBody
{
    /**
     *
     * @var ?RetrieveLabelReallocationLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\RetrieveLabelReallocationLinks|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?RetrieveLabelReallocationLinks $links = null;

    /**
     *
     * @var ?\DateTime $created
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $created = null;

    /**
     * @param  ?RetrieveLabelReallocationLinks  $links
     * @param  ?\DateTime  $created
     * @phpstan-pure
     */
    public function __construct(?RetrieveLabelReallocationLinks $links = null, ?\DateTime $created = null)
    {
        $this->links = $links;
        $this->created = $created;
    }
}