<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Utils\SpeakeasyMetadata;
class RetrieveLabelReallocationRequest
{
    /**
     * Label reallocation unique identifier
     *
     * @var string $reallocationId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=reallocationId')]
    public string $reallocationId;

    /**
     * @param  string  $reallocationId
     * @phpstan-pure
     */
    public function __construct(string $reallocationId)
    {
        $this->reallocationId = $reallocationId;
    }
}