<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


/** SettlementAccountBalanceResponse - Response for retrieving balance of a settlement account with bankUsageType = card-network */
class SettlementAccountBalanceResponse
{
    /**
     *
     * @var GetFundingSourceBalanceLinks2 $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\GetFundingSourceBalanceLinks2')]
    public GetFundingSourceBalanceLinks2 $links;

    /**
     *
     * @var Available2 $available
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('available')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\Available2')]
    public Available2 $available;

    /**
     * @param  GetFundingSourceBalanceLinks2  $links
     * @param  Available2  $available
     * @phpstan-pure
     */
    public function __construct(GetFundingSourceBalanceLinks2 $links, Available2 $available)
    {
        $this->links = $links;
        $this->available = $available;
    }
}