<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Models\Components;
use Dwolla\Utils\SpeakeasyMetadata;
class UpdateOrRemoveFundingSourceRequest
{
    /**
     * Funding source unique identifier
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     * Parameters to update a customer funding source
     *
     * @var Components\UpdateUnverifiedBank|Components\UpdateVerifiedBank|Components\RemoveBank $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\UpdateUnverifiedBank|Components\UpdateVerifiedBank|Components\RemoveBank $body;

    /**
     * @param  string  $id
     * @param  Components\UpdateUnverifiedBank|Components\UpdateVerifiedBank|Components\RemoveBank  $body
     * @phpstan-pure
     */
    public function __construct(string $id, Components\UpdateUnverifiedBank|Components\UpdateVerifiedBank|Components\RemoveBank $body)
    {
        $this->id = $id;
        $this->body = $body;
    }
}