<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Models\Components;
use Dwolla\Utils\SpeakeasyMetadata;
class UpdateRequest
{
    /**
     * Customer unique identifier
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     * Parameters for updating a Customer
     *
     * @var Components\DeactivateCustomer|Components\ReactivateCustomer|Components\SuspendCustomer|Components\UpdateUnverifiedAndReceiveOnly|Components\UpdateVerifiedPersonal|Components\UpdateVerifiedBusiness|Components\UpgradeToUnverified|Components\UpgradeToVerifiedPersonal|Components\UpgradeToVerifiedBusiness|Components\UpgradeToVerifiedSoleProp|Components\RetryVerifiedPersonal|Components\RetryVerifiedBusinessNoController|Components\RetryVerifiedBusinessWithController|Components\RetryVerifiedBusinessWithInternationalController|Components\RetryVerifiedSoleProp $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\DeactivateCustomer|Components\ReactivateCustomer|Components\SuspendCustomer|Components\UpdateUnverifiedAndReceiveOnly|Components\UpdateVerifiedPersonal|Components\UpdateVerifiedBusiness|Components\UpgradeToUnverified|Components\UpgradeToVerifiedPersonal|Components\UpgradeToVerifiedBusiness|Components\UpgradeToVerifiedSoleProp|Components\RetryVerifiedPersonal|Components\RetryVerifiedBusinessNoController|Components\RetryVerifiedBusinessWithController|Components\RetryVerifiedBusinessWithInternationalController|Components\RetryVerifiedSoleProp $body;

    /**
     * @param  string  $id
     * @param  Components\DeactivateCustomer|Components\ReactivateCustomer|Components\SuspendCustomer|Components\UpdateUnverifiedAndReceiveOnly|Components\UpdateVerifiedPersonal|Components\UpdateVerifiedBusiness|Components\UpgradeToUnverified|Components\UpgradeToVerifiedPersonal|Components\UpgradeToVerifiedBusiness|Components\UpgradeToVerifiedSoleProp|Components\RetryVerifiedPersonal|Components\RetryVerifiedBusinessNoController|Components\RetryVerifiedBusinessWithController|Components\RetryVerifiedBusinessWithInternationalController|Components\RetryVerifiedSoleProp  $body
     * @phpstan-pure
     */
    public function __construct(string $id, Components\DeactivateCustomer|Components\ReactivateCustomer|Components\SuspendCustomer|Components\UpdateUnverifiedAndReceiveOnly|Components\UpdateVerifiedPersonal|Components\UpdateVerifiedBusiness|Components\UpgradeToUnverified|Components\UpgradeToVerifiedPersonal|Components\UpgradeToVerifiedBusiness|Components\UpgradeToVerifiedSoleProp|Components\RetryVerifiedPersonal|Components\RetryVerifiedBusinessNoController|Components\RetryVerifiedBusinessWithController|Components\RetryVerifiedBusinessWithInternationalController|Components\RetryVerifiedSoleProp $body)
    {
        $this->id = $id;
        $this->body = $body;
    }
}