<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


/** UpdateWebhookSubscriptionRequestBody - Parameters to update a webhook subscription */
class UpdateWebhookSubscriptionRequestBody
{
    /**
     *
     * @var bool $paused
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paused')]
    public bool $paused;

    /**
     * @param  bool  $paused
     * @phpstan-pure
     */
    public function __construct(bool $paused)
    {
        $this->paused = $paused;
    }
}