<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Models\Components;
class UpdateResponse
{
    /**
     * HTTP response content type for this operation
     *
     * @var string $contentType
     */
    public string $contentType;

    /**
     * HTTP response status code for this operation
     *
     * @var int $statusCode
     */
    public int $statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var \Psr\Http\Message\ResponseInterface $rawResponse
     */
    public \Psr\Http\Message\ResponseInterface $rawResponse;

    /**
     * successful operation
     *
     * @var Components\UnverifiedCustomer|Components\ReceiveOnlyCustomer|Components\VerifiedPersonalCustomer|Components\VerifiedSolePropCustomer|Components\VerifiedBusinessCustomer|null $oneOf
     */
    public Components\UnverifiedCustomer|Components\ReceiveOnlyCustomer|Components\VerifiedPersonalCustomer|Components\VerifiedSolePropCustomer|Components\VerifiedBusinessCustomer|null $oneOf = null;

    /**
     * @param  string  $contentType
     * @param  int  $statusCode
     * @param  \Psr\Http\Message\ResponseInterface  $rawResponse
     * @param  Components\UnverifiedCustomer|Components\ReceiveOnlyCustomer|Components\VerifiedPersonalCustomer|Components\VerifiedSolePropCustomer|Components\VerifiedBusinessCustomer|null  $oneOf
     * @phpstan-pure
     */
    public function __construct(string $contentType, int $statusCode, \Psr\Http\Message\ResponseInterface $rawResponse, Components\UnverifiedCustomer|Components\ReceiveOnlyCustomer|Components\VerifiedPersonalCustomer|Components\VerifiedSolePropCustomer|Components\VerifiedBusinessCustomer|null $oneOf = null)
    {
        $this->contentType = $contentType;
        $this->statusCode = $statusCode;
        $this->rawResponse = $rawResponse;
        $this->oneOf = $oneOf;
    }
}