<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


class VerifyMicroDepositsLinks
{
    /**
     *
     * @var ?VerifyMicroDepositsSelf $self
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('self')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\VerifyMicroDepositsSelf|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?VerifyMicroDepositsSelf $self = null;

    /**
     * @param  ?VerifyMicroDepositsSelf  $self
     * @phpstan-pure
     */
    public function __construct(?VerifyMicroDepositsSelf $self = null)
    {
        $this->self = $self;
    }
}