<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


/** VerifyKbaQuestionsResponseBody - created */
class VerifyKbaQuestionsResponseBody
{
    /**
     *
     * @var ?VerifyKbaQuestionsLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Operations\VerifyKbaQuestionsLinks|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?VerifyKbaQuestionsLinks $links = null;

    /**
     *
     * @var ?string $verificationStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verificationStatus')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $verificationStatus = null;

    /**
     * @param  ?VerifyKbaQuestionsLinks  $links
     * @param  ?string  $verificationStatus
     * @phpstan-pure
     */
    public function __construct(?VerifyKbaQuestionsLinks $links = null, ?string $verificationStatus = null)
    {
        $this->links = $links;
        $this->verificationStatus = $verificationStatus;
    }
}