<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;


/** VerifyKbaQuestionsRequestBody - Parameters for verifying KBA questions */
class VerifyKbaQuestionsRequestBody
{
    /**
     * $answers
     *
     * @var array<VerifyKbaQuestionsAnswer> $answers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('answers')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dwolla\Models\Operations\VerifyKbaQuestionsAnswer>')]
    public array $answers;

    /**
     * @param  array<VerifyKbaQuestionsAnswer>  $answers
     * @phpstan-pure
     */
    public function __construct(array $answers)
    {
        $this->answers = $answers;
    }
}