<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Operations;

use Dwolla\Utils\SpeakeasyMetadata;
class VerifyKbaQuestionsRequest
{
    /**
     * The id of the KBA session to verify questions for.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     * Parameters for verifying KBA questions
     *
     * @var VerifyKbaQuestionsRequestBody $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public VerifyKbaQuestionsRequestBody $body;

    /**
     * @param  string  $id
     * @param  VerifyKbaQuestionsRequestBody  $body
     * @phpstan-pure
     */
    public function __construct(string $id, VerifyKbaQuestionsRequestBody $body)
    {
        $this->id = $id;
        $this->body = $body;
    }
}