<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class AllFailureReason
{
    /**
     * Failure reason code
     *
     * @var string $reason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reason')]
    public string $reason;

    /**
     * Human-readable explanation of the failure reason
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * @param  string  $reason
     * @param  string  $description
     * @phpstan-pure
     */
    public function __construct(string $reason, string $description)
    {
        $this->reason = $reason;
        $this->description = $description;
    }
}