<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class Attempt
{
    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?Request $request
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('request')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\Request|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Request $request = null;

    /**
     *
     * @var ?Response $response
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('response')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\Response|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Response $response = null;

    /**
     * @param  ?string  $id
     * @param  ?Request  $request
     * @param  ?Response  $response
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?Request $request = null, ?Response $response = null)
    {
        $this->id = $id;
        $this->request = $request;
        $this->response = $response;
    }
}