<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class AvailableExchangeConnection
{
    /**
     * Token representing the external bank account that can be used to create a funding source
     *
     * @var string $availableConnectionToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('availableConnectionToken')]
    public string $availableConnectionToken;

    /**
     * Name of the external bank account
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * @param  string  $availableConnectionToken
     * @param  string  $name
     * @phpstan-pure
     */
    public function __construct(string $availableConnectionToken, string $name)
    {
        $this->availableConnectionToken = $availableConnectionToken;
        $this->name = $name;
    }
}