<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** BeneficialOwner - Request body model for a Beneficial Owner */
class BeneficialOwner
{
    /**
     * $links
     *
     * @var array<string, \Dwolla\Models\Components\HalLink> $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, \Dwolla\Models\Components\HalLink>')]
    public array $links;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     *
     * @var \Dwolla\Models\Components\InternationalAddress $address
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\InternationalAddress')]
    public InternationalAddress $address;

    /**
     *
     * @var \Dwolla\Models\Components\VerificationStatus $verificationStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verificationStatus')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\VerificationStatus')]
    public VerificationStatus $verificationStatus;

    /**
     *
     * @var \DateTime $created
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created')]
    public \DateTime $created;

    /**
     * @param  array<string, \Dwolla\Models\Components\HalLink>  $links
     * @param  string  $id
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  \Dwolla\Models\Components\InternationalAddress  $address
     * @param  \Dwolla\Models\Components\VerificationStatus  $verificationStatus
     * @param  \DateTime  $created
     * @phpstan-pure
     */
    public function __construct(array $links, string $id, string $firstName, string $lastName, InternationalAddress $address, VerificationStatus $verificationStatus, \DateTime $created)
    {
        $this->links = $links;
        $this->id = $id;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->address = $address;
        $this->verificationStatus = $verificationStatus;
        $this->created = $created;
    }
}