<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** BeneficialOwners - Request model for list beneficial owners */
class BeneficialOwners
{
    /**
     * $links
     *
     * @var ?array<string, \Dwolla\Models\Components\HalLink> $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, \Dwolla\Models\Components\HalLink>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $links = null;

    /**
     *
     * @var ?\Dwolla\Models\Components\BeneficialOwnersEmbedded $embedded
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_embedded')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\BeneficialOwnersEmbedded|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BeneficialOwnersEmbedded $embedded = null;

    /**
     * @param  ?array<string, \Dwolla\Models\Components\HalLink>  $links
     * @param  ?\Dwolla\Models\Components\BeneficialOwnersEmbedded  $embedded
     * @phpstan-pure
     */
    public function __construct(?array $links = null, ?BeneficialOwnersEmbedded $embedded = null)
    {
        $this->links = $links;
        $this->embedded = $embedded;
    }
}