<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class BeneficialOwnersEmbedded
{
    /**
     * $beneficialOwners
     *
     * @var ?array<BeneficialOwner> $beneficialOwners
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('beneficial-owners')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dwolla\Models\Components\BeneficialOwner>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $beneficialOwners = null;

    /**
     * @param  ?array<BeneficialOwner>  $beneficialOwners
     * @phpstan-pure
     */
    public function __construct(?array $beneficialOwners = null)
    {
        $this->beneficialOwners = $beneficialOwners;
    }
}