<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class BusinessClassificationLinks
{
    /**
     *
     * @var ?HalLink $self
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('self')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\HalLink|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?HalLink $self = null;

    /**
     * @param  ?HalLink  $self
     * @phpstan-pure
     */
    public function __construct(?HalLink $self = null)
    {
        $this->self = $self;
    }
}