<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class CannotParseAmountErrorEmbedded
{
    /**
     * $errors
     *
     * @var ?array<CannotParseAmountErrorError> $errors
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('errors')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dwolla\Models\Components\CannotParseAmountErrorError>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $errors = null;

    /**
     * @param  ?array<CannotParseAmountErrorError>  $errors
     * @phpstan-pure
     */
    public function __construct(?array $errors = null)
    {
        $this->errors = $errors;
    }
}