<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class CannotParseAmountErrorError
{
    /**
     *
     * @var ?string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $code = null;

    /**
     *
     * @var ?string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $message = null;

    /**
     *
     * @var ?string $path
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('path')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $path = null;

    /**
     *
     * @var ?CannotParseAmountErrorLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CannotParseAmountErrorLinks|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CannotParseAmountErrorLinks $links = null;

    /**
     * @param  ?string  $code
     * @param  ?string  $message
     * @param  ?string  $path
     * @param  ?CannotParseAmountErrorLinks  $links
     * @phpstan-pure
     */
    public function __construct(?string $code = null, ?string $message = null, ?string $path = null, ?CannotParseAmountErrorLinks $links = null)
    {
        $this->code = $code;
        $this->message = $message;
        $this->path = $path;
        $this->links = $links;
    }
}