<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class CardSourceNotAllowedErrorError
{
    /**
     *
     * @var Code $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\Code')]
    public Code $code;

    /**
     *
     * @var Message $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\Message')]
    public Message $message;

    /**
     *
     * @var Path $path
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('path')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\Path')]
    public Path $path;

    /**
     *
     * @var ?CardSourceNotAllowedErrorLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CardSourceNotAllowedErrorLinks|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CardSourceNotAllowedErrorLinks $links = null;

    /**
     * @param  Code  $code
     * @param  Message  $message
     * @param  Path  $path
     * @param  ?CardSourceNotAllowedErrorLinks  $links
     * @phpstan-pure
     */
    public function __construct(Code $code, Message $message, Path $path, ?CardSourceNotAllowedErrorLinks $links = null)
    {
        $this->code = $code;
        $this->message = $message;
        $this->path = $path;
        $this->links = $links;
    }
}