<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/**
 * CreateCustomerExchangeSessionForCardCardDetails - Optional. Opt into Account Name Inquiry (ANI) for this session by providing the expected
 *
 * cardholder name. Retrieve the resulting match on the Exchange with `GET /exchanges/{id}`.
 *
 */
class CreateCustomerExchangeSessionForCardCardDetails
{
    /**
     * The cardholder first name you expect on the card.
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     * The cardholder last name you expect on the card.
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     * Set to `true` to request an Account Name Inquiry (ANI) name-match check on the card.
     *
     * @var bool $accountNameInquiry
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accountNameInquiry')]
    public bool $accountNameInquiry;

    /**
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  bool  $accountNameInquiry
     * @phpstan-pure
     */
    public function __construct(string $firstName, string $lastName, bool $accountNameInquiry)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->accountNameInquiry = $accountNameInquiry;
    }
}