<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class CreateCustomerExchangeSessionForCardLinks
{
    /**
     *
     * @var \Dwolla\Models\Components\CreateCustomerExchangeSessionForCardExchangePartner $exchangePartner
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exchange-partner')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateCustomerExchangeSessionForCardExchangePartner')]
    public CreateCustomerExchangeSessionForCardExchangePartner $exchangePartner;

    /**
     * @param  \Dwolla\Models\Components\CreateCustomerExchangeSessionForCardExchangePartner  $exchangePartner
     * @phpstan-pure
     */
    public function __construct(CreateCustomerExchangeSessionForCardExchangePartner $exchangePartner)
    {
        $this->exchangePartner = $exchangePartner;
    }
}