<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class CreateCustomerCardFundingSourceWithExchangeCardDetails
{
    /**
     * Cardholder first name
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     * Cardholder last name
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     * The billing address associated with the card
     *
     * @var CreateCustomerCardFundingSourceWithExchangeBillingAddress $billingAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billingAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateCustomerCardFundingSourceWithExchangeBillingAddress')]
    public CreateCustomerCardFundingSourceWithExchangeBillingAddress $billingAddress;

    /**
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  CreateCustomerCardFundingSourceWithExchangeBillingAddress  $billingAddress
     * @phpstan-pure
     */
    public function __construct(string $firstName, string $lastName, CreateCustomerCardFundingSourceWithExchangeBillingAddress $billingAddress)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->billingAddress = $billingAddress;
    }
}