<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** CreateCustomerBankFundingSourceWithPlaid - Schema for creating a bank funding source using a Plaid processor token. */
class CreateCustomerBankFundingSourceWithPlaid
{
    /**
     * A processor token obtained from Plaid for adding and verifying a bank
     *
     * @var string $plaidToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('plaidToken')]
    public string $plaidToken;

    /**
     * Type of bank account
     *
     * @var CreateCustomerBankFundingSourceWithPlaidBankAccountType $bankAccountType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccountType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateCustomerBankFundingSourceWithPlaidBankAccountType')]
    public CreateCustomerBankFundingSourceWithPlaidBankAccountType $bankAccountType;

    /**
     * Arbitrary nickname for the funding source. Must be 50 characters or less.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * An array containing a list of processing channels. ACH is the default processing channel for bank transfers.
     *
     * @var ?array<CreateCustomerBankFundingSourceWithPlaidChannel> $channels
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('channels')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dwolla\Models\Components\CreateCustomerBankFundingSourceWithPlaidChannel>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $channels = null;

    /**
     *
     * @var ?CreateCustomerBankFundingSourceWithPlaidLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateCustomerBankFundingSourceWithPlaidLinks|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateCustomerBankFundingSourceWithPlaidLinks $links = null;

    /**
     * @param  string  $plaidToken
     * @param  CreateCustomerBankFundingSourceWithPlaidBankAccountType  $bankAccountType
     * @param  string  $name
     * @param  ?array<CreateCustomerBankFundingSourceWithPlaidChannel>  $channels
     * @param  ?CreateCustomerBankFundingSourceWithPlaidLinks  $links
     * @phpstan-pure
     */
    public function __construct(string $plaidToken, CreateCustomerBankFundingSourceWithPlaidBankAccountType $bankAccountType, string $name, ?array $channels = null, ?CreateCustomerBankFundingSourceWithPlaidLinks $links = null)
    {
        $this->plaidToken = $plaidToken;
        $this->bankAccountType = $bankAccountType;
        $this->name = $name;
        $this->channels = $channels;
        $this->links = $links;
    }
}