<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class CreateCustomerBankFundingSourceWithPlaidLinks
{
    /**
     *
     * @var ?CreateCustomerBankFundingSourceWithPlaidOnDemandAuthorization $onDemandAuthorization
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('on-demand-authorization')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateCustomerBankFundingSourceWithPlaidOnDemandAuthorization|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateCustomerBankFundingSourceWithPlaidOnDemandAuthorization $onDemandAuthorization = null;

    /**
     * @param  ?CreateCustomerBankFundingSourceWithPlaidOnDemandAuthorization  $onDemandAuthorization
     * @phpstan-pure
     */
    public function __construct(?CreateCustomerBankFundingSourceWithPlaidOnDemandAuthorization $onDemandAuthorization = null)
    {
        $this->onDemandAuthorization = $onDemandAuthorization;
    }
}