<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** Type of bank account */
enum CreateCustomerBankFundingSourceWithPlaidBankAccountType: string
{
    case Checking = 'checking';
    case Savings = 'savings';
}
