<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class CreateCustomerExchangeSessionWithRedirectLinks
{
    /**
     *
     * @var CreateCustomerExchangeSessionWithRedirectExchangePartner $exchangePartner
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exchange-partner')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateCustomerExchangeSessionWithRedirectExchangePartner')]
    public CreateCustomerExchangeSessionWithRedirectExchangePartner $exchangePartner;

    /**
     *
     * @var CreateCustomerExchangeSessionWithRedirectRedirectUrl $redirectUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('redirect-url')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateCustomerExchangeSessionWithRedirectRedirectUrl')]
    public CreateCustomerExchangeSessionWithRedirectRedirectUrl $redirectUrl;

    /**
     * @param  CreateCustomerExchangeSessionWithRedirectExchangePartner  $exchangePartner
     * @param  CreateCustomerExchangeSessionWithRedirectRedirectUrl  $redirectUrl
     * @phpstan-pure
     */
    public function __construct(CreateCustomerExchangeSessionWithRedirectExchangePartner $exchangePartner, CreateCustomerExchangeSessionWithRedirectRedirectUrl $redirectUrl)
    {
        $this->exchangePartner = $exchangePartner;
        $this->redirectUrl = $redirectUrl;
    }
}