<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** The kind of government identification document provided. */
enum CreateCustomerCardFundingSourceWithExchangeType: string
{
    case Passport = 'passport';
    case License = 'license';
    case IdCard = 'idCard';
    case TaxId = 'taxId';
}
