<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** CreateVerifiedBusinessCustomerWithInternationalController - Create a Verified Business customer with an international (non US) controller */
class CreateVerifiedBusinessCustomerWithInternationalController
{
    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     *
     * @var string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public string $email;

    /**
     *
     * @var string $address1
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address1')]
    public string $address1;

    /**
     *
     * @var string $city
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
    public string $city;

    /**
     *
     * @var string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    public string $state;

    /**
     *
     * @var string $postalCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postalCode')]
    public string $postalCode;

    /**
     *
     * @var string $businessClassification
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('businessClassification')]
    public string $businessClassification;

    /**
     *
     * @var string $businessName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('businessName')]
    public string $businessName;

    /**
     *
     * @var string $ein
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ein')]
    public string $ein;

    /**
     *
     * @var CreateVerifiedBusinessCustomerWithInternationalControllerController $controller
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('controller')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateVerifiedBusinessCustomerWithInternationalControllerController')]
    public CreateVerifiedBusinessCustomerWithInternationalControllerController $controller;

    /**
     *
     * @var CreateVerifiedBusinessCustomerWithInternationalControllerBusinessType $businessType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('businessType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateVerifiedBusinessCustomerWithInternationalControllerBusinessType')]
    public CreateVerifiedBusinessCustomerWithInternationalControllerBusinessType $businessType;

    /**
     *
     * @var ?string $ipAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ipAddress')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ipAddress = null;

    /**
     *
     * @var ?string $phone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phone = null;

    /**
     *
     * @var ?string $correlationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('correlationId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $correlationId = null;

    /**
     *
     * @var ?string $address2
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address2')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $address2 = null;

    /**
     *
     * @var ?string $doingBusinessAs
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('doingBusinessAs')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $doingBusinessAs = null;

    /**
     *
     * @var ?string $website
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('website')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $website = null;

    /**
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  string  $email
     * @param  string  $type
     * @param  string  $address1
     * @param  string  $city
     * @param  string  $state
     * @param  string  $postalCode
     * @param  string  $businessClassification
     * @param  string  $businessName
     * @param  string  $ein
     * @param  CreateVerifiedBusinessCustomerWithInternationalControllerController  $controller
     * @param  CreateVerifiedBusinessCustomerWithInternationalControllerBusinessType  $businessType
     * @param  ?string  $ipAddress
     * @param  ?string  $phone
     * @param  ?string  $correlationId
     * @param  ?string  $address2
     * @param  ?string  $doingBusinessAs
     * @param  ?string  $website
     * @phpstan-pure
     */
    public function __construct(string $firstName, string $lastName, string $email, string $address1, string $city, string $state, string $postalCode, string $businessClassification, string $businessName, string $ein, CreateVerifiedBusinessCustomerWithInternationalControllerController $controller, CreateVerifiedBusinessCustomerWithInternationalControllerBusinessType $businessType, ?string $ipAddress = null, ?string $phone = null, ?string $correlationId = null, ?string $address2 = null, ?string $doingBusinessAs = null, ?string $website = null, string $type = 'business')
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->email = $email;
        $this->address1 = $address1;
        $this->city = $city;
        $this->state = $state;
        $this->postalCode = $postalCode;
        $this->businessClassification = $businessClassification;
        $this->businessName = $businessName;
        $this->ein = $ein;
        $this->controller = $controller;
        $this->businessType = $businessType;
        $this->ipAddress = $ipAddress;
        $this->phone = $phone;
        $this->correlationId = $correlationId;
        $this->address2 = $address2;
        $this->doingBusinessAs = $doingBusinessAs;
        $this->website = $website;
        $this->type = $type;
    }
}