<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/**
 * CreateCustomerExchangeSessionForCard - Create an exchange session for debit card capture (Push to Card).
 *
 *
 * Optionally opt into Account Name Inquiry (ANI) by passing `cardDetails` with the cardholder
 * name you expect on the card. The name-match result is returned on the resulting Exchange as
 * `cardDetails.accountNameInquiry`, giving you an early signal of fraudulent card usage before
 * you create a funding source.
 *
 */
class CreateCustomerExchangeSessionForCard
{
    /**
     *
     * @var \Dwolla\Models\Components\CreateCustomerExchangeSessionForCardLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateCustomerExchangeSessionForCardLinks')]
    public CreateCustomerExchangeSessionForCardLinks $links;

    /**
     * Optional. Opt into Account Name Inquiry (ANI) for this session by providing the expected
     *
     * cardholder name. Retrieve the resulting match on the Exchange with `GET /exchanges/{id}`.
     *
     *
     * @var ?\Dwolla\Models\Components\CreateCustomerExchangeSessionForCardCardDetails $cardDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cardDetails')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateCustomerExchangeSessionForCardCardDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateCustomerExchangeSessionForCardCardDetails $cardDetails = null;

    /**
     * @param  \Dwolla\Models\Components\CreateCustomerExchangeSessionForCardLinks  $links
     * @param  ?\Dwolla\Models\Components\CreateCustomerExchangeSessionForCardCardDetails  $cardDetails
     * @phpstan-pure
     */
    public function __construct(CreateCustomerExchangeSessionForCardLinks $links, ?CreateCustomerExchangeSessionForCardCardDetails $cardDetails = null)
    {
        $this->links = $links;
        $this->cardDetails = $cardDetails;
    }
}