<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class CreateTokenBasedExchangeLinks
{
    /**
     *
     * @var CreateTokenBasedExchangeExchangePartner $exchangePartner
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exchange-partner')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateTokenBasedExchangeExchangePartner')]
    public CreateTokenBasedExchangeExchangePartner $exchangePartner;

    /**
     * @param  CreateTokenBasedExchangeExchangePartner  $exchangePartner
     * @phpstan-pure
     */
    public function __construct(CreateTokenBasedExchangeExchangePartner $exchangePartner)
    {
        $this->exchangePartner = $exchangePartner;
    }
}