<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** CreateCustomerVirtualAccountFundingSource - Schema for creating a Virtual Account Number (VAN) . VANs are unique account numbers for receiving external transactions into a Dwolla Balance. */
class CreateCustomerVirtualAccountFundingSource
{
    /**
     * Arbitrary nickname for the funding source. Must be 50 characters or less.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Type of funding source. Must be set to "virtual" for VAN creation.
     *
     * @var CreateCustomerVirtualAccountFundingSourceType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateCustomerVirtualAccountFundingSourceType')]
    public CreateCustomerVirtualAccountFundingSourceType $type;

    /**
     * Type of bank account. Must be "checking" for Virtual Account Numbers.
     *
     * @var CreateCustomerVirtualAccountFundingSourceBankAccountType $bankAccountType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccountType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateCustomerVirtualAccountFundingSourceBankAccountType')]
    public CreateCustomerVirtualAccountFundingSourceBankAccountType $bankAccountType;

    /**
     * @param  string  $name
     * @param  CreateCustomerVirtualAccountFundingSourceType  $type
     * @param  CreateCustomerVirtualAccountFundingSourceBankAccountType  $bankAccountType
     * @phpstan-pure
     */
    public function __construct(string $name, CreateCustomerVirtualAccountFundingSourceType $type, CreateCustomerVirtualAccountFundingSourceBankAccountType $bankAccountType)
    {
        $this->name = $name;
        $this->type = $type;
        $this->bankAccountType = $bankAccountType;
    }
}