<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** CreateReAuthExchangeSessionForWeb - Create re-auth exchange session for web (Plaid web sessions where request body is optional) */
class CreateReAuthExchangeSessionForWeb
{

    public function __construct()
    {
    }
}