<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class CreateAccountFundingSource
{
    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var CreateAccountFundingSourceBankAccountType $bankAccountType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccountType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateAccountFundingSourceBankAccountType')]
    public CreateAccountFundingSourceBankAccountType $bankAccountType;

    /**
     *
     * @var string $accountNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accountNumber')]
    public string $accountNumber;

    /**
     *
     * @var string $routingNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('routingNumber')]
    public string $routingNumber;

    /**
     *
     * @var ?CreateAccountFundingSourceLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateAccountFundingSourceLinks|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateAccountFundingSourceLinks $links = null;

    /**
     * $channels
     *
     * @var ?array<string> $channels
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('channels')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $channels = null;

    /**
     * @param  string  $name
     * @param  CreateAccountFundingSourceBankAccountType  $bankAccountType
     * @param  string  $accountNumber
     * @param  string  $routingNumber
     * @param  ?CreateAccountFundingSourceLinks  $links
     * @param  ?array<string>  $channels
     * @phpstan-pure
     */
    public function __construct(string $name, CreateAccountFundingSourceBankAccountType $bankAccountType, string $accountNumber, string $routingNumber, ?CreateAccountFundingSourceLinks $links = null, ?array $channels = null)
    {
        $this->name = $name;
        $this->bankAccountType = $bankAccountType;
        $this->accountNumber = $accountNumber;
        $this->routingNumber = $routingNumber;
        $this->links = $links;
        $this->channels = $channels;
    }
}