<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** Type of bank account */
enum CreateCustomerBankFundingSourceWithAccountNumbersBankAccountType: string
{
    case Checking = 'checking';
    case Savings = 'savings';
    case GeneralLedger = 'general-ledger';
    case Loan = 'loan';
}
