<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class CreateFinicitySecureExchange
{
    /**
     *
     * @var \Dwolla\Models\Components\CreateFinicitySecureExchangeLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateFinicitySecureExchangeLinks')]
    public CreateFinicitySecureExchangeLinks $links;

    /**
     *
     * @var \Dwolla\Models\Components\Finicity $finicity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('finicity')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\Finicity')]
    public Finicity $finicity;

    /**
     * @param  \Dwolla\Models\Components\CreateFinicitySecureExchangeLinks  $links
     * @param  \Dwolla\Models\Components\Finicity  $finicity
     * @phpstan-pure
     */
    public function __construct(CreateFinicitySecureExchangeLinks $links, Finicity $finicity)
    {
        $this->links = $links;
        $this->finicity = $finicity;
    }
}