<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** CreateReAuthExchangeSessionWithRedirect - Create re-auth exchange session with redirect URL (required for mobile sessions with Plaid) */
class CreateReAuthExchangeSessionWithRedirect
{
    /**
     *
     * @var CreateReAuthExchangeSessionWithRedirectLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateReAuthExchangeSessionWithRedirectLinks')]
    public CreateReAuthExchangeSessionWithRedirectLinks $links;

    /**
     * @param  CreateReAuthExchangeSessionWithRedirectLinks  $links
     * @phpstan-pure
     */
    public function __construct(CreateReAuthExchangeSessionWithRedirectLinks $links)
    {
        $this->links = $links;
    }
}