<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class CreateCustomerExchangeFundingSourceLinks
{
    /**
     *
     * @var CreateCustomerExchangeFundingSourceExchange $exchange
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exchange')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateCustomerExchangeFundingSourceExchange')]
    public CreateCustomerExchangeFundingSourceExchange $exchange;

    /**
     *
     * @var ?CreateCustomerExchangeFundingSourceOnDemandAuthorization $onDemandAuthorization
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('on-demand-authorization')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateCustomerExchangeFundingSourceOnDemandAuthorization|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateCustomerExchangeFundingSourceOnDemandAuthorization $onDemandAuthorization = null;

    /**
     * @param  CreateCustomerExchangeFundingSourceExchange  $exchange
     * @param  ?CreateCustomerExchangeFundingSourceOnDemandAuthorization  $onDemandAuthorization
     * @phpstan-pure
     */
    public function __construct(CreateCustomerExchangeFundingSourceExchange $exchange, ?CreateCustomerExchangeFundingSourceOnDemandAuthorization $onDemandAuthorization = null)
    {
        $this->exchange = $exchange;
        $this->onDemandAuthorization = $onDemandAuthorization;
    }
}