<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class CreatePlaidOpenBankingExchange
{
    /**
     *
     * @var \Dwolla\Models\Components\CreatePlaidOpenBankingExchangeLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreatePlaidOpenBankingExchangeLinks')]
    public CreatePlaidOpenBankingExchangeLinks $links;

    /**
     *
     * @var \Dwolla\Models\Components\Plaid $plaid
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('plaid')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\Plaid')]
    public Plaid $plaid;

    /**
     * @param  \Dwolla\Models\Components\CreatePlaidOpenBankingExchangeLinks  $links
     * @param  \Dwolla\Models\Components\Plaid  $plaid
     * @phpstan-pure
     */
    public function __construct(CreatePlaidOpenBankingExchangeLinks $links, Plaid $plaid)
    {
        $this->links = $links;
        $this->plaid = $plaid;
    }
}