<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** CreateUSBeneficialOwner - Create a US Beneficial Owner (identified by SSN). For US-based beneficial owners only. Use SSN for identity verification instead of passport. */
class CreateUSBeneficialOwner
{
    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     *
     * @var string $dateOfBirth
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dateOfBirth')]
    public string $dateOfBirth;

    /**
     *
     * @var InternationalAddress $address
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\InternationalAddress')]
    public InternationalAddress $address;

    /**
     *
     * @var string $ssn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ssn')]
    public string $ssn;

    /**
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  string  $dateOfBirth
     * @param  InternationalAddress  $address
     * @param  string  $ssn
     * @phpstan-pure
     */
    public function __construct(string $firstName, string $lastName, string $dateOfBirth, InternationalAddress $address, string $ssn)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->dateOfBirth = $dateOfBirth;
        $this->address = $address;
        $this->ssn = $ssn;
    }
}