<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** Type of bank account. Must be "checking" for Virtual Account Numbers. */
enum CreateCustomerVirtualAccountFundingSourceBankAccountType: string
{
    case Checking = 'checking';
}
