<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class CreatePlaidOpenBankingExchangeLinks
{
    /**
     *
     * @var CreatePlaidOpenBankingExchangeExchangePartner $exchangePartner
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exchange-partner')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreatePlaidOpenBankingExchangeExchangePartner')]
    public CreatePlaidOpenBankingExchangeExchangePartner $exchangePartner;

    /**
     * @param  CreatePlaidOpenBankingExchangeExchangePartner  $exchangePartner
     * @phpstan-pure
     */
    public function __construct(CreatePlaidOpenBankingExchangeExchangePartner $exchangePartner)
    {
        $this->exchangePartner = $exchangePartner;
    }
}