<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class CreateMXOpenBankingExchange
{
    /**
     *
     * @var CreateMXOpenBankingExchangeLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\CreateMXOpenBankingExchangeLinks')]
    public CreateMXOpenBankingExchangeLinks $links;

    /**
     *
     * @var Mx $mx
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mx')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\Mx')]
    public Mx $mx;

    /**
     * @param  CreateMXOpenBankingExchangeLinks  $links
     * @param  Mx  $mx
     * @phpstan-pure
     */
    public function __construct(CreateMXOpenBankingExchangeLinks $links, Mx $mx)
    {
        $this->links = $links;
        $this->mx = $mx;
    }
}