<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class DirectAccountWithoutBankErrorEmbedded
{
    /**
     * $errors
     *
     * @var ?array<DirectAccountWithoutBankErrorError> $errors
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('errors')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dwolla\Models\Components\DirectAccountWithoutBankErrorError>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $errors = null;

    /**
     * @param  ?array<DirectAccountWithoutBankErrorError>  $errors
     * @phpstan-pure
     */
    public function __construct(?array $errors = null)
    {
        $this->errors = $errors;
    }
}