<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class Documents
{
    /**
     * $links
     *
     * @var array<string, HalLink> $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, \Dwolla\Models\Components\HalLink>')]
    public array $links;

    /**
     *
     * @var DocumentsEmbedded $embedded
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_embedded')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\DocumentsEmbedded')]
    public DocumentsEmbedded $embedded;

    /**
     *
     * @var int $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    public int $total;

    /**
     * @param  array<string, HalLink>  $links
     * @param  DocumentsEmbedded  $embedded
     * @param  int  $total
     * @phpstan-pure
     */
    public function __construct(array $links, DocumentsEmbedded $embedded, int $total)
    {
        $this->links = $links;
        $this->embedded = $embedded;
        $this->total = $total;
    }
}