<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class Event
{
    /**
     * $links
     *
     * @var ?array<string, HalLink> $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, \Dwolla\Models\Components\HalLink>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $links = null;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?\DateTime $created
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $created = null;

    /**
     *
     * @var ?string $topic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('topic')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $topic = null;

    /**
     *
     * @var ?string $resourceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('resourceId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $resourceId = null;

    /**
     * @param  ?array<string, HalLink>  $links
     * @param  ?string  $id
     * @param  ?\DateTime  $created
     * @param  ?string  $topic
     * @param  ?string  $resourceId
     * @phpstan-pure
     */
    public function __construct(?array $links = null, ?string $id = null, ?\DateTime $created = null, ?string $topic = null, ?string $resourceId = null)
    {
        $this->links = $links;
        $this->id = $id;
        $this->created = $created;
        $this->topic = $topic;
        $this->resourceId = $resourceId;
    }
}