<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class EventsEmbedded
{
    /**
     * $events
     *
     * @var ?array<Event> $events
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('events')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dwolla\Models\Components\Event>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $events = null;

    /**
     * @param  ?array<Event>  $events
     * @phpstan-pure
     */
    public function __construct(?array $events = null)
    {
        $this->events = $events;
    }
}