<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/**
 * ExchangeCardDetails - Card-specific details. Only present for card exchanges where an Account Name Inquiry (ANI)
 *
 * was requested on the exchange session.
 *
 */
class ExchangeCardDetails
{
    /**
     * The result of comparing the expected cardholder name supplied on the exchange session
     *
     * against the name the card issuer has on file.
     * - `full-match`: the expected name matched the name on file.
     * - `partial-match`: part of the expected name matched, for example the last name only.
     * - `no-match`: the expected name did not match the name on file.
     * - `not-performed`: ANI was not requested, or the check did not run.
     * - `not-supported`: the card issuer or network does not support ANI.
     *
     *
     * @var \Dwolla\Models\Components\AccountNameInquiry $accountNameInquiry
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accountNameInquiry')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\AccountNameInquiry')]
    public AccountNameInquiry $accountNameInquiry;

    /**
     * @param  \Dwolla\Models\Components\AccountNameInquiry  $accountNameInquiry
     * @phpstan-pure
     */
    public function __construct(AccountNameInquiry $accountNameInquiry)
    {
        $this->accountNameInquiry = $accountNameInquiry;
    }
}