<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class ExchangePartner
{
    /**
     * $links
     *
     * @var array<string, HalLink> $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, \Dwolla\Models\Components\HalLink>')]
    public array $links;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var Name $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\Name')]
    public Name $name;

    /**
     *
     * @var ExchangePartnerStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\ExchangePartnerStatus')]
    public ExchangePartnerStatus $status;

    /**
     *
     * @var \DateTime $created
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created')]
    public \DateTime $created;

    /**
     * @param  array<string, HalLink>  $links
     * @param  string  $id
     * @param  Name  $name
     * @param  ExchangePartnerStatus  $status
     * @param  \DateTime  $created
     * @phpstan-pure
     */
    public function __construct(array $links, string $id, Name $name, ExchangePartnerStatus $status, \DateTime $created)
    {
        $this->links = $links;
        $this->id = $id;
        $this->name = $name;
        $this->status = $status;
        $this->created = $created;
    }
}