<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** FedNowDetails - FedNow Service network specific details. Present when transfer was processed via FedNow network. */
class FedNowDetails
{
    /**
     * FedNow destination details with network identifiers
     *
     * @var ?FedNowDetailsDestination $destination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\FedNowDetailsDestination|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?FedNowDetailsDestination $destination = null;

    /**
     * @param  ?FedNowDetailsDestination  $destination
     * @phpstan-pure
     */
    public function __construct(?FedNowDetailsDestination $destination = null)
    {
        $this->destination = $destination;
    }
}