<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class Finicity
{
    /**
     *
     * @var ?int $profile
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('profile')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $profile = null;

    /**
     *
     * @var ?string $version
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('version')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $version = null;

    /**
     *
     * @var ?string $receiptId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('receiptId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $receiptId = null;

    /**
     *
     * @var ?string $receiptVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('receiptVersion')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $receiptVersion = null;

    /**
     *
     * @var ?string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customerId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customerId = null;

    /**
     *
     * @var ?int $partnerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('partnerId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $partnerId = null;

    /**
     * $products
     *
     * @var ?array<Product> $products
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('products')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dwolla\Models\Components\Product>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $products = null;

    /**
     *
     * @var ?\DateTime $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $timestamp = null;

    /**
     * @param  ?int  $profile
     * @param  ?string  $version
     * @param  ?string  $receiptId
     * @param  ?string  $receiptVersion
     * @param  ?string  $customerId
     * @param  ?int  $partnerId
     * @param  ?array<Product>  $products
     * @param  ?\DateTime  $timestamp
     * @phpstan-pure
     */
    public function __construct(?int $profile = null, ?string $version = null, ?string $receiptId = null, ?string $receiptVersion = null, ?string $customerId = null, ?int $partnerId = null, ?array $products = null, ?\DateTime $timestamp = null)
    {
        $this->profile = $profile;
        $this->version = $version;
        $this->receiptId = $receiptId;
        $this->receiptVersion = $receiptVersion;
        $this->customerId = $customerId;
        $this->partnerId = $partnerId;
        $this->products = $products;
        $this->timestamp = $timestamp;
    }
}