<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


enum FundingSourceChannel: string
{
    case Ach = 'ach';
    case RealTimePayments = 'real-time-payments';
    case Wire = 'wire';
    case External = 'external';
}
