<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** FundingSourceCardDetails - Card-specific details. Only present when type is 'card'. */
class FundingSourceCardDetails
{
    /**
     * The card brand/network (e.g., Visa, Mastercard, American Express)
     *
     * @var ?string $brand
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('brand')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $brand = null;

    /**
     * The last four digits of the card number
     *
     * @var ?string $lastFour
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastFour')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $lastFour = null;

    /**
     * The card expiration month (1-12)
     *
     * @var ?int $expirationMonth
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expirationMonth')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $expirationMonth = null;

    /**
     * The card expiration year (4-digit year)
     *
     * @var ?int $expirationYear
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expirationYear')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $expirationYear = null;

    /**
     * The cardholder name as it appears on the card
     *
     * @var ?string $nameOnCard
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nameOnCard')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $nameOnCard = null;

    /**
     * Bank Identification Number (BIN) - the first 6-8 digits of the card number
     *
     * @var ?string $bin
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bin')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bin = null;

    /**
     * The billing address associated with the card
     *
     * @var ?\Dwolla\Models\Components\FundingSourceBillingAddress $billingAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billingAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\FundingSourceBillingAddress|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?FundingSourceBillingAddress $billingAddress = null;

    /**
     * Cardholder date of birth in `YYYY-MM-DD` format. Only present if it was supplied when the card funding source was created or updated.
     *
     * @var ?string $dateOfBirth
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dateOfBirth')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $dateOfBirth = null;

    /**
     * Cardholder country of birth as a two-letter country code (ISO 3166-1 alpha-2). Only present if it was supplied when the card funding source was created or updated.
     *
     * @var ?string $countryOfBirth
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('countryOfBirth')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $countryOfBirth = null;

    /**
     * @param  ?string  $brand
     * @param  ?string  $lastFour
     * @param  ?int  $expirationMonth
     * @param  ?int  $expirationYear
     * @param  ?string  $nameOnCard
     * @param  ?string  $bin
     * @param  ?\Dwolla\Models\Components\FundingSourceBillingAddress  $billingAddress
     * @param  ?string  $dateOfBirth
     * @param  ?string  $countryOfBirth
     * @phpstan-pure
     */
    public function __construct(?string $brand = null, ?string $lastFour = null, ?int $expirationMonth = null, ?int $expirationYear = null, ?string $nameOnCard = null, ?string $bin = null, ?FundingSourceBillingAddress $billingAddress = null, ?string $dateOfBirth = null, ?string $countryOfBirth = null)
    {
        $this->brand = $brand;
        $this->lastFour = $lastFour;
        $this->expirationMonth = $expirationMonth;
        $this->expirationYear = $expirationYear;
        $this->nameOnCard = $nameOnCard;
        $this->bin = $bin;
        $this->billingAddress = $billingAddress;
        $this->dateOfBirth = $dateOfBirth;
        $this->countryOfBirth = $countryOfBirth;
    }
}