<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class InvalidCardTokenErrorEmbedded
{
    /**
     * $errors
     *
     * @var array<InvalidCardTokenErrorError> $errors
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('errors')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dwolla\Models\Components\InvalidCardTokenErrorError>')]
    public array $errors;

    /**
     * @param  array<InvalidCardTokenErrorError>  $errors
     * @phpstan-pure
     */
    public function __construct(array $errors)
    {
        $this->errors = $errors;
    }
}