<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class InvalidTokenErrorEmbedded
{
    /**
     * $errors
     *
     * @var array<\Dwolla\Models\Components\InvalidTokenErrorError> $errors
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('errors')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dwolla\Models\Components\InvalidTokenErrorError>')]
    public array $errors;

    /**
     * @param  array<\Dwolla\Models\Components\InvalidTokenErrorError>  $errors
     * @phpstan-pure
     */
    public function __construct(array $errors)
    {
        $this->errors = $errors;
    }
}