<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class Labels
{
    /**
     * $links
     *
     * @var ?array<string, HalLink> $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, \Dwolla\Models\Components\HalLink>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $links = null;

    /**
     *
     * @var ?LabelsEmbedded $embedded
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_embedded')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\LabelsEmbedded|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LabelsEmbedded $embedded = null;

    /**
     *
     * @var ?int $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $total = null;

    /**
     * @param  ?array<string, HalLink>  $links
     * @param  ?LabelsEmbedded  $embedded
     * @param  ?int  $total
     * @phpstan-pure
     */
    public function __construct(?array $links = null, ?LabelsEmbedded $embedded = null, ?int $total = null)
    {
        $this->links = $links;
        $this->embedded = $embedded;
        $this->total = $total;
    }
}