<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class LabelLedgerEntry
{
    /**
     * $links
     *
     * @var ?array<string, HalLink> $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, \Dwolla\Models\Components\HalLink>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $links = null;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?LabelLedgerEntryAmount $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\LabelLedgerEntryAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LabelLedgerEntryAmount $amount = null;

    /**
     *
     * @var ?\DateTime $created
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $created = null;

    /**
     * @param  ?array<string, HalLink>  $links
     * @param  ?string  $id
     * @param  ?LabelLedgerEntryAmount  $amount
     * @param  ?\DateTime  $created
     * @phpstan-pure
     */
    public function __construct(?array $links = null, ?string $id = null, ?LabelLedgerEntryAmount $amount = null, ?\DateTime $created = null)
    {
        $this->links = $links;
        $this->id = $id;
        $this->amount = $amount;
        $this->created = $created;
    }
}