<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class MaximumCardsExceededErrorError
{
    /**
     *
     * @var string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    public string $code;

    /**
     *
     * @var string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    public string $message;

    /**
     *
     * @var string $path
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('path')]
    public string $path;

    /**
     * @param  string  $code
     * @param  string  $message
     * @param  string  $path
     * @phpstan-pure
     */
    public function __construct(string $code, string $message, string $path)
    {
        $this->code = $code;
        $this->message = $message;
        $this->path = $path;
    }
}