<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class OnDemandAuthorizationLinks
{
    /**
     *
     * @var ?OnDemandAuthorizationSelf $self
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('self')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\OnDemandAuthorizationSelf|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OnDemandAuthorizationSelf $self = null;

    /**
     * @param  ?OnDemandAuthorizationSelf  $self
     * @phpstan-pure
     */
    public function __construct(?OnDemandAuthorizationSelf $self = null)
    {
        $this->self = $self;
    }
}