<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** ReactivateCustomer - Reactivate a Customer */
class ReactivateCustomer
{
    /**
     *
     * @var string $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    public string $status;

    /**
     * @param  string  $status
     * @phpstan-pure
     */
    public function __construct(string $status)
    {
        $this->status = $status;
    }
}