<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


enum ReceiveOnlyCustomerType: string
{
    case ReceiveOnly = 'receive-only';
}
