<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class RetryVerifiedBusinessWithInternationalControllerController
{
    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     *
     * @var string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     *
     * @var string $dateOfBirth
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dateOfBirth')]
    public string $dateOfBirth;

    /**
     *
     * @var RetryVerifiedBusinessWithInternationalControllerAddress $address
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\RetryVerifiedBusinessWithInternationalControllerAddress')]
    public RetryVerifiedBusinessWithInternationalControllerAddress $address;

    /**
     *
     * @var RetryVerifiedBusinessWithInternationalControllerPassport $passport
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('passport')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\RetryVerifiedBusinessWithInternationalControllerPassport')]
    public RetryVerifiedBusinessWithInternationalControllerPassport $passport;

    /**
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  string  $title
     * @param  string  $dateOfBirth
     * @param  RetryVerifiedBusinessWithInternationalControllerAddress  $address
     * @param  RetryVerifiedBusinessWithInternationalControllerPassport  $passport
     * @phpstan-pure
     */
    public function __construct(string $firstName, string $lastName, string $title, string $dateOfBirth, RetryVerifiedBusinessWithInternationalControllerAddress $address, RetryVerifiedBusinessWithInternationalControllerPassport $passport)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->title = $title;
        $this->dateOfBirth = $dateOfBirth;
        $this->address = $address;
        $this->passport = $passport;
    }
}