<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class RetryVerifiedBusinessWithControllerController
{
    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     *
     * @var string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     *
     * @var string $ssn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ssn')]
    public string $ssn;

    /**
     *
     * @var string $dateOfBirth
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dateOfBirth')]
    public string $dateOfBirth;

    /**
     *
     * @var RetryVerifiedBusinessWithControllerAddress $address
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\RetryVerifiedBusinessWithControllerAddress')]
    public RetryVerifiedBusinessWithControllerAddress $address;

    /**
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  string  $title
     * @param  string  $ssn
     * @param  string  $dateOfBirth
     * @param  RetryVerifiedBusinessWithControllerAddress  $address
     * @phpstan-pure
     */
    public function __construct(string $firstName, string $lastName, string $title, string $ssn, string $dateOfBirth, RetryVerifiedBusinessWithControllerAddress $address)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->title = $title;
        $this->ssn = $ssn;
        $this->dateOfBirth = $dateOfBirth;
        $this->address = $address;
    }
}