<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class RetryLinks
{
    /**
     *
     * @var ?RetrySelf $self
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('self')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\RetrySelf|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?RetrySelf $self = null;

    /**
     *
     * @var ?WebhookRetriesWebhook $webhook
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('webhook')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\WebhookRetriesWebhook|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?WebhookRetriesWebhook $webhook = null;

    /**
     * @param  ?RetrySelf  $self
     * @param  ?WebhookRetriesWebhook  $webhook
     * @phpstan-pure
     */
    public function __construct(?RetrySelf $self = null, ?WebhookRetriesWebhook $webhook = null)
    {
        $this->self = $self;
        $this->webhook = $webhook;
    }
}