<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** SandboxSimulationBankProcessingResponse - Response when simulating bank transfer processing (200 OK). */
class SandboxSimulationBankProcessingResponse
{
    /**
     * Count of bank transfers (and related items) affected by the simulation run.
     *
     * @var int $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    public int $total;

    /**
     *
     * @var SandboxSimulationBankProcessingResponseLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\SandboxSimulationBankProcessingResponseLinks')]
    public SandboxSimulationBankProcessingResponseLinks $links;

    /**
     * @param  int  $total
     * @param  SandboxSimulationBankProcessingResponseLinks  $links
     * @phpstan-pure
     */
    public function __construct(int $total, SandboxSimulationBankProcessingResponseLinks $links)
    {
        $this->total = $total;
        $this->links = $links;
    }
}