<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** Verification directive that was simulated. */
enum SandboxSimulationCustomerVerificationResponseErrorCode: string
{
    case PersonalIDRequired = 'PersonalIDRequired';
    case POBoxNotAllowed = 'POBoxNotAllowed';
    case AddressNotAssociatedWithBusiness = 'AddressNotAssociatedWithBusiness';
    case EINDocumentRequired = 'EINDocumentRequired';
}
