<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/**
 * SandboxSimulationVirtualAccountTransfersRequest - Simulate Virtual Account Number (VAN) / external transfers in Sandbox. Up to 10 transfers per request;
 *
 * transfers are created and processed immediately. Successful response is 202 Accepted.
 *
 */
class SandboxSimulationVirtualAccountTransfersRequest
{
    /**
     * Transfers to simulate (max 10 per request).
     *
     * @var array<SandboxSimulationVirtualTransferItem> $transfers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transfers')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dwolla\Models\Components\SandboxSimulationVirtualTransferItem>')]
    public array $transfers;

    /**
     * Must be set to virtual for VAN transfer simulation.
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * @param  string  $type
     * @param  array<SandboxSimulationVirtualTransferItem>  $transfers
     * @phpstan-pure
     */
    public function __construct(array $transfers, string $type = 'virtual')
    {
        $this->transfers = $transfers;
        $this->type = $type;
    }
}