<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/**
 * SandboxSimulationBankProcessingRequest - Omit the request body or send an empty JSON object (`{}`). Triggers processing (or failure) for the last
 *
 * 500 bank transfers on the authorized application or Sandbox account, and initiated micro-deposits.
 * Successful response is 200 with a HAL body including total.
 *
 */
class SandboxSimulationBankProcessingRequest
{

    public function __construct()
    {
    }
}