<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/**
 * SandboxSimulationCustomerVerificationResponse - Response when simulating customer verification directives (200 OK). Echoes the simulated `errorCode`;
 *
 * retrieve the Customer resource to inspect `_embedded.errors`.
 *
 */
class SandboxSimulationCustomerVerificationResponse
{
    /**
     *
     * @var \Dwolla\Models\Components\SandboxSimulationCustomerVerificationResponseLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\SandboxSimulationCustomerVerificationResponseLinks')]
    public SandboxSimulationCustomerVerificationResponseLinks $links;

    /**
     * Verification directive that was simulated.
     *
     * @var \Dwolla\Models\Components\SandboxSimulationCustomerVerificationResponseErrorCode $errorCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('errorCode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\SandboxSimulationCustomerVerificationResponseErrorCode')]
    public SandboxSimulationCustomerVerificationResponseErrorCode $errorCode;

    /**
     * @param  \Dwolla\Models\Components\SandboxSimulationCustomerVerificationResponseLinks  $links
     * @param  \Dwolla\Models\Components\SandboxSimulationCustomerVerificationResponseErrorCode  $errorCode
     * @phpstan-pure
     */
    public function __construct(SandboxSimulationCustomerVerificationResponseLinks $links, SandboxSimulationCustomerVerificationResponseErrorCode $errorCode)
    {
        $this->links = $links;
        $this->errorCode = $errorCode;
    }
}