<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class SandboxSimulationCustomerVerificationRequestLinks
{
    /**
     *
     * @var SandboxSimulationCustomerVerificationRequestCustomer $customer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\SandboxSimulationCustomerVerificationRequestCustomer')]
    public SandboxSimulationCustomerVerificationRequestCustomer $customer;

    /**
     * @param  SandboxSimulationCustomerVerificationRequestCustomer  $customer
     * @phpstan-pure
     */
    public function __construct(SandboxSimulationCustomerVerificationRequestCustomer $customer)
    {
        $this->customer = $customer;
    }
}