<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** SandboxSimulationVirtualTransferItem - One simulated external (VAN) transfer in a sandbox-simulations request. */
class SandboxSimulationVirtualTransferItem
{
    /**
     * Link wrapper for the destination funding source (Dwolla HAL-style single link).
     *
     * @var Link $link
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_link')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\Link')]
    public Link $link;

    /**
     *
     * @var TransferAmount $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\TransferAmount')]
    public TransferAmount $amount;

    /**
     * @param  Link  $link
     * @param  TransferAmount  $amount
     * @phpstan-pure
     */
    public function __construct(Link $link, TransferAmount $amount)
    {
        $this->link = $link;
        $this->amount = $amount;
    }
}