<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class TransferProcessingChannel
{
    /**
     * The payment network used to process the transfer
     *
     * @var ?DestinationEnum $destination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\DestinationEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?DestinationEnum $destination = null;

    /**
     * @param  ?DestinationEnum  $destination
     * @phpstan-pure
     */
    public function __construct(?DestinationEnum $destination = null)
    {
        $this->destination = $destination;
    }
}