<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** UpdateVerifiedBank - Request body for updating information of a Verified bank funding source */
class UpdateVerifiedBank
{
    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * @param  string  $name
     * @phpstan-pure
     */
    public function __construct(string $name)
    {
        $this->name = $name;
    }
}