<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/**
 * UpdateCardFundingSourceBillingAddress - The billing address associated with the card. When you include `billingAddress`,
 *
 * `postalCode` is required.
 *
 */
class UpdateCardFundingSourceBillingAddress
{
    /**
     * Postal code or ZIP code
     *
     * @var string $postalCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postalCode')]
    public string $postalCode;

    /**
     * First line of the street address. Must be 50 characters or less.
     *
     * @var ?string $address1
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address1')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $address1 = null;

    /**
     * Second line of the street address (optional). Must be 100 characters or less.
     *
     * @var ?string $address2
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address2')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $address2 = null;

    /**
     * Third line of the street address (optional). Must be 100 characters or less.
     *
     * @var ?string $address3
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address3')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $address3 = null;

    /**
     * City name. Must be 50 characters or less.
     *
     * @var ?string $city
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $city = null;

    /**
     * Two-letter state, province, or region code.
     *
     * @var ?string $stateProvinceRegion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('stateProvinceRegion')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $stateProvinceRegion = null;

    /**
     * Two-letter country code (ISO 3166-1 alpha-2)
     *
     * @var ?string $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $country = null;

    /**
     * @param  string  $postalCode
     * @param  ?string  $address1
     * @param  ?string  $address2
     * @param  ?string  $address3
     * @param  ?string  $city
     * @param  ?string  $stateProvinceRegion
     * @param  ?string  $country
     * @phpstan-pure
     */
    public function __construct(string $postalCode, ?string $address1 = null, ?string $address2 = null, ?string $address3 = null, ?string $city = null, ?string $stateProvinceRegion = null, ?string $country = null)
    {
        $this->postalCode = $postalCode;
        $this->address1 = $address1;
        $this->address2 = $address2;
        $this->address3 = $address3;
        $this->city = $city;
        $this->stateProvinceRegion = $stateProvinceRegion;
        $this->country = $country;
    }
}