<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** UpdateUnverifiedAndReceiveOnly - Update Unverified Customer or Receive Only User Information */
class UpdateUnverifiedAndReceiveOnly
{
    /**
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $firstName = null;

    /**
     *
     * @var ?string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $lastName = null;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     *
     * @var ?string $businessName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('businessName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $businessName = null;

    /**
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     * @param  ?string  $email
     * @param  ?string  $businessName
     * @phpstan-pure
     */
    public function __construct(?string $firstName = null, ?string $lastName = null, ?string $email = null, ?string $businessName = null)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->email = $email;
        $this->businessName = $businessName;
    }
}