<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/**
 * UpdateCardFundingSource - Request body for updating a debit card funding source.
 *
 *
 * Every field is optional, but you must provide at least one. Only the fields you send are
 * changed; omitted fields keep their current values. Use this operation to add or update the
 * optional cardholder identity fields - `dateOfBirth`, `countryOfBirth`, and `identification` -
 * on a card funding source that already exists.
 *
 * Card funding sources cannot be updated with bank fields such as `routingNumber`,
 * `accountNumber`, `bankAccountType`, or `bankAccountHolderType`.
 *
 */
class UpdateCardFundingSource
{
    /**
     * Arbitrary nickname for the debit card funding source. Must be 50 characters or less.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * Cardholder details to add or update. Provide only the fields you want to change.
     *
     * @var ?\Dwolla\Models\Components\UpdateCardFundingSourceCardDetails $cardDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cardDetails')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\UpdateCardFundingSourceCardDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateCardFundingSourceCardDetails $cardDetails = null;

    /**
     * @param  ?string  $name
     * @param  ?\Dwolla\Models\Components\UpdateCardFundingSourceCardDetails  $cardDetails
     * @phpstan-pure
     */
    public function __construct(?string $name = null, ?UpdateCardFundingSourceCardDetails $cardDetails = null)
    {
        $this->name = $name;
        $this->cardDetails = $cardDetails;
    }
}