<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** UpgradeToUnverified - Upgrade Receive Only User to Unverified Customer */
class UpgradeToUnverified
{
    /**
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * @param  string  $type
     * @phpstan-pure
     */
    public function __construct(string $type)
    {
        $this->type = $type;
    }
}