<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class UpgradeToVerifiedBusinessController
{
    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     *
     * @var string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     *
     * @var string $dateOfBirth
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dateOfBirth')]
    public string $dateOfBirth;

    /**
     *
     * @var UpgradeToVerifiedBusinessAddress $address
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\UpgradeToVerifiedBusinessAddress')]
    public UpgradeToVerifiedBusinessAddress $address;

    /**
     *
     * @var ?string $ssn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ssn')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ssn = null;

    /**
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  string  $title
     * @param  string  $dateOfBirth
     * @param  UpgradeToVerifiedBusinessAddress  $address
     * @param  ?string  $ssn
     * @phpstan-pure
     */
    public function __construct(string $firstName, string $lastName, string $title, string $dateOfBirth, UpgradeToVerifiedBusinessAddress $address, ?string $ssn = null)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->title = $title;
        $this->dateOfBirth = $dateOfBirth;
        $this->address = $address;
        $this->ssn = $ssn;
    }
}