<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


/** UpgradeToVerifiedSoleProp - Upgrade Unverified Customer to Verified Business Customer (Sole Proprietorship) */
class UpgradeToVerifiedSoleProp
{
    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     *
     * @var string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public string $email;

    /**
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     *
     * @var string $dateOfBirth
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dateOfBirth')]
    public string $dateOfBirth;

    /**
     *
     * @var string $ssn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ssn')]
    public string $ssn;

    /**
     *
     * @var string $address1
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address1')]
    public string $address1;

    /**
     *
     * @var string $city
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
    public string $city;

    /**
     *
     * @var string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    public string $state;

    /**
     *
     * @var string $postalCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postalCode')]
    public string $postalCode;

    /**
     *
     * @var string $businessClassification
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('businessClassification')]
    public string $businessClassification;

    /**
     *
     * @var string $businessType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('businessType')]
    public string $businessType;

    /**
     *
     * @var string $businessName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('businessName')]
    public string $businessName;

    /**
     *
     * @var string $ein
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ein')]
    public string $ein;

    /**
     *
     * @var ?string $ipAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ipAddress')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ipAddress = null;

    /**
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  string  $email
     * @param  string  $type
     * @param  string  $dateOfBirth
     * @param  string  $ssn
     * @param  string  $address1
     * @param  string  $city
     * @param  string  $state
     * @param  string  $postalCode
     * @param  string  $businessClassification
     * @param  string  $businessType
     * @param  string  $businessName
     * @param  string  $ein
     * @param  ?string  $ipAddress
     * @phpstan-pure
     */
    public function __construct(string $firstName, string $lastName, string $email, string $type, string $dateOfBirth, string $ssn, string $address1, string $city, string $state, string $postalCode, string $businessClassification, string $businessType, string $businessName, string $ein, ?string $ipAddress = null)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->email = $email;
        $this->type = $type;
        $this->dateOfBirth = $dateOfBirth;
        $this->ssn = $ssn;
        $this->address1 = $address1;
        $this->city = $city;
        $this->state = $state;
        $this->postalCode = $postalCode;
        $this->businessClassification = $businessClassification;
        $this->businessType = $businessType;
        $this->businessName = $businessName;
        $this->ein = $ein;
        $this->ipAddress = $ipAddress;
    }
}