<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


enum VerifiedPersonalCustomerStatus: string
{
    case Verified = 'verified';
    case Suspended = 'suspended';
    case Deactivated = 'deactivated';
    case Document = 'document';
    case Retry = 'retry';
    case Kba = 'kba';
}
