<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


enum VerifiedBusinessCustomerBusinessType: string
{
    case Llc = 'llc';
    case Corporation = 'corporation';
    case Partnership = 'partnership';
}
