<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class VerifiedBusinessCustomerAddress
{
    /**
     *
     * @var ?string $address1
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address1')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $address1 = null;

    /**
     *
     * @var ?string $address2
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address2')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $address2 = null;

    /**
     *
     * @var ?string $address3
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address3')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $address3 = null;

    /**
     *
     * @var ?string $city
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $city = null;

    /**
     *
     * @var ?string $postalCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postalCode')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $postalCode = null;

    /**
     *
     * @var ?string $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $country = null;

    /**
     *
     * @var ?string $stateProvinceRegion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('stateProvinceRegion')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $stateProvinceRegion = null;

    /**
     * @param  ?string  $address1
     * @param  ?string  $address2
     * @param  ?string  $address3
     * @param  ?string  $city
     * @param  ?string  $postalCode
     * @param  ?string  $country
     * @param  ?string  $stateProvinceRegion
     * @phpstan-pure
     */
    public function __construct(?string $address1 = null, ?string $address2 = null, ?string $address3 = null, ?string $city = null, ?string $postalCode = null, ?string $country = null, ?string $stateProvinceRegion = null)
    {
        $this->address1 = $address1;
        $this->address2 = $address2;
        $this->address3 = $address3;
        $this->city = $city;
        $this->postalCode = $postalCode;
        $this->country = $country;
        $this->stateProvinceRegion = $stateProvinceRegion;
    }
}