<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class VerifiedBusinessCustomerController
{
    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public string $lastName;

    /**
     *
     * @var string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     *
     * @var VerifiedBusinessCustomerAddress $address
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\VerifiedBusinessCustomerAddress')]
    public VerifiedBusinessCustomerAddress $address;

    /**
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  string  $title
     * @param  VerifiedBusinessCustomerAddress  $address
     * @phpstan-pure
     */
    public function __construct(string $firstName, string $lastName, string $title, VerifiedBusinessCustomerAddress $address)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->title = $title;
        $this->address = $address;
    }
}