<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class WebhookRetriesEmbedded
{
    /**
     * $retries
     *
     * @var ?array<\Dwolla\Models\Components\WebhookRetriesRetry> $retries
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('retries')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dwolla\Models\Components\WebhookRetriesRetry>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $retries = null;

    /**
     * @param  ?array<\Dwolla\Models\Components\WebhookRetriesRetry>  $retries
     * @phpstan-pure
     */
    public function __construct(?array $retries = null)
    {
        $this->retries = $retries;
    }
}