<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class WebhookRetriesLinks
{
    /**
     *
     * @var ?WebhookRetriesSelf $self
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('self')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\WebhookRetriesSelf|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?WebhookRetriesSelf $self = null;

    /**
     * @param  ?WebhookRetriesSelf  $self
     * @phpstan-pure
     */
    public function __construct(?WebhookRetriesSelf $self = null)
    {
        $this->self = $self;
    }
}