<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class Webhook
{
    /**
     *
     * @var ?WebhookLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\WebhookLinks|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?WebhookLinks $links = null;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?string $topic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('topic')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $topic = null;

    /**
     *
     * @var ?string $accountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accountId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $accountId = null;

    /**
     *
     * @var ?string $eventId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('eventId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $eventId = null;

    /**
     *
     * @var ?string $subscriptionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscriptionId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $subscriptionId = null;

    /**
     * $attempts
     *
     * @var ?array<Attempt> $attempts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attempts')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Dwolla\Models\Components\Attempt>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $attempts = null;

    /**
     * @param  ?WebhookLinks  $links
     * @param  ?string  $id
     * @param  ?string  $topic
     * @param  ?string  $accountId
     * @param  ?string  $eventId
     * @param  ?string  $subscriptionId
     * @param  ?array<Attempt>  $attempts
     * @phpstan-pure
     */
    public function __construct(?WebhookLinks $links = null, ?string $id = null, ?string $topic = null, ?string $accountId = null, ?string $eventId = null, ?string $subscriptionId = null, ?array $attempts = null)
    {
        $this->links = $links;
        $this->id = $id;
        $this->topic = $topic;
        $this->accountId = $accountId;
        $this->eventId = $eventId;
        $this->subscriptionId = $subscriptionId;
        $this->attempts = $attempts;
    }
}