<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class WebhookRetriesRetry
{
    /**
     *
     * @var ?RetryLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\RetryLinks|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?RetryLinks $links = null;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?\DateTime $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $timestamp = null;

    /**
     * @param  ?RetryLinks  $links
     * @param  ?string  $id
     * @param  ?\DateTime  $timestamp
     * @phpstan-pure
     */
    public function __construct(?RetryLinks $links = null, ?string $id = null, ?\DateTime $timestamp = null)
    {
        $this->links = $links;
        $this->id = $id;
        $this->timestamp = $timestamp;
    }
}