<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class WebhookSubscription
{
    /**
     *
     * @var ?WebhookSubscriptionLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\WebhookSubscriptionLinks|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?WebhookSubscriptionLinks $links = null;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $url = null;

    /**
     *
     * @var ?bool $paused
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paused')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $paused = null;

    /**
     *
     * @var ?\DateTime $created
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $created = null;

    /**
     * @param  ?WebhookSubscriptionLinks  $links
     * @param  ?string  $id
     * @param  ?string  $url
     * @param  ?bool  $paused
     * @param  ?\DateTime  $created
     * @phpstan-pure
     */
    public function __construct(?WebhookSubscriptionLinks $links = null, ?string $id = null, ?string $url = null, ?bool $paused = null, ?\DateTime $created = null)
    {
        $this->links = $links;
        $this->id = $id;
        $this->url = $url;
        $this->paused = $paused;
        $this->created = $created;
    }
}