<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla\Models\Components;


class WebhookRetries
{
    /**
     *
     * @var ?WebhookRetriesLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\WebhookRetriesLinks|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?WebhookRetriesLinks $links = null;

    /**
     *
     * @var ?WebhookRetriesEmbedded $embedded
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('_embedded')]
    #[\Speakeasy\Serializer\Annotation\Type('\Dwolla\Models\Components\WebhookRetriesEmbedded|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?WebhookRetriesEmbedded $embedded = null;

    /**
     *
     * @var ?int $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $total = null;

    /**
     * @param  ?WebhookRetriesLinks  $links
     * @param  ?WebhookRetriesEmbedded  $embedded
     * @param  ?int  $total
     * @phpstan-pure
     */
    public function __construct(?WebhookRetriesLinks $links = null, ?WebhookRetriesEmbedded $embedded = null, ?int $total = null)
    {
        $this->links = $links;
        $this->embedded = $embedded;
        $this->total = $total;
    }
}