<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dwolla;

use Dwolla\Utils\Retry;

/**
 * DwollaBuilder is used to configure and build an instance of the SDK.
 */
class DwollaBuilder
{
    public function __construct(
        private SDKConfiguration $sdkConfig = new SDKConfiguration(),
    ) {
    }

    /**
     * setClient allows setting a custom Guzzle client for the SDK to make requests with.
     *
     * @param  \GuzzleHttp\ClientInterface  $client
     * @return DwollaBuilder
     */
    public function setClient(\GuzzleHttp\ClientInterface $client): DwollaBuilder
    {
        $this->sdkConfig->client = $client;

        return $this;
    }

    /**
     * setSecurity is used to configure the security required for the SDK.
     *
     * @param  Models\Components\Security  $security
     * @return DwollaBuilder
     */
    public function setSecurity(Models\Components\Security $security): DwollaBuilder
    {
        $this->sdkConfig->securitySource = fn () => $security;

        return $this;
    }

    /**
     * setSecuritySource is usd to configure the security required for the SDK.
     * unlike setSecurity, setSecuritySource accepts a closure that will be called to retrieve the security information.
     *
     * @param  pure-Closure(): Models\Components\Security  $securitySource
     * @return DwollaBuilder
     */
    public function setSecuritySource(\Closure $securitySource): DwollaBuilder
    {
        $this->sdkConfig->securitySource = $securitySource;

        return $this;
    }

    /**
     * setServerUrl is used to configure the server URL for the SDK, and optionally template any parameters in the URL.
     *
     * @param  string  $serverUrl
     * @param  array<string, string>  $params
     * @return DwollaBuilder
     */
    public function setServerUrl(string $serverUrl, ?array $params = null): DwollaBuilder
    {
        $this->sdkConfig->serverUrl = Utils\Utils::templateUrl($serverUrl, $params);

        return $this;
    }

    /**
     * setServer is used to configure the server for the SDK
     *
     * @param  string  $server
     * @return DwollaBuilder
     */
    public function setServer(string $server): DwollaBuilder
    {
        $this->sdkConfig->server = $server;

        return $this;
    }

    public function setRetryConfig(Retry\RetryConfig $config): DwollaBuilder
    {
        $this->sdkConfig->retryConfig = $config;

        return $this;
    }

    /**
     * build is used to build the SDK with any of the configured options.
     *
     * @return Dwolla
     */
    public function build(): Dwolla
    {
        if ($this->sdkConfig->client === null) {
            $this->sdkConfig->client = new \GuzzleHttp\Client([
                'timeout' => 60,
            ]);
        }
        if ($this->sdkConfig->hasSecurity()) {
            $this->sdkConfig->client = Utils\Utils::configureSecurityClient($this->sdkConfig->client, $this->sdkConfig->getSecurity());
        }

        return new Dwolla($this->sdkConfig);
    }
}